### PR TITLE
Update LZW31-SN Parameters for 1.47

### PR DESCRIPTION
**Pull request by DelusionalAI**
The newest firmware for the LZW31-SN adds 2 new parameters. Details can be found [here](https://support.inovelli.com/portal/en/kb/articles/firmware-v1-47-beta-lzw31-sn-dimmer-red-series-gen-2).

Config parameters name and description pulled from the Hubitat "driver"

### CODE REVIEW

**Comment by DelusionalAI** [comment]
XML test is angry because I didn't make a new revision for replacing a typo. Otherwise its fine.

**Comment by SirDeadlystrike** [comment]
@DelusionalAI are you going to make a PR for the rest of the switches for instant on? 

Would it make sense to do each switch individually or 1 PR for all 4?

**Comment by DelusionalAI** [comment]
I don't own the others so I didn't notice that the others had an update as well. I agree it would make sense, I'll see about adding them.

**Comment by SirDeadlystrike** [comment]
LZW30-SN
LZW31-SN
LZW30
LZW31

Its the exact same xml/config/params on each switch. You can copy paste. If you check the InovelliUSA/OpenZwave repo its already updated there.

**Comment by DelusionalAI** [comment]
Added the other switches, included the instant on for all switches, and the smart bulb mode for the dimmers. Thanks for that info @SirDeadlystrike

**Comment by Fishwaldo** [comment]
Thanks

**Pull request merged**
