### PR TITLE
Fix yrd110, yrd120 lock xmls

### PR DESCRIPTION
**Pull request by GeekGoneOld**
Moved these two devices out of PushButtonDeadbolt.xml and TouchDeadbolt.xml respectively.  These are zw300, not 500 and operate differently.

### CODE REVIEW

**Review by firstof9 — CHANGES_REQUESTED** [review]
You need to bump the version number on line 2 of manufacturer_specific.xml.

https://github.com/OpenZWave/open-zwave/blob/cbdd3b91bbfc598e736a06fb2d8239976009639e/config/manufacturer_specific.xml#L2

**Comment by GeekGoneOld** [comment]
Done.

At first I thought I could start the new file at revision at 1 but I thought about what you said and it seems obvious that the revision is not a file issue, it is a device (mfg, id, type) issue so I made the revision one higher than the higher of the two devices were previously.  Many thanks.

**Comment by firstof9** [comment]
There you go, checks have passed 👍

**Review by firstof9 — APPROVED** [review]

**Comment by Fishwaldo** [comment]
Thanks!

**Pull request merged**
