### PR TITLE
Adding new Inovelli Switch devices LZW30 & LZW30-SN

### PR DESCRIPTION
**Pull request by InovelliUSA**

### CODE REVIEW

**Comment by Fishwaldo** [comment]
It would be great if you could include the metadata and product pics as well! Please see the wiki (https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices)

**Comment by erocm123** [comment]
Yes, I will do that asap.

**Comment by InovelliUSA** [comment]
Ok, metadata and images have been added.

**Comment by InovelliUSA** [comment]
Awesome, thanks!

**Comment by DeviantEng** [comment]
@InovelliUSA Can you also submit configs for your gen 2 dimmer switches (red and black series)?  I'm not seeing them in open-zwave currently.

Thanks!

**Comment by InovelliUSA** [comment]
Thanks for reaching out. We are still testing them before submitting the merge request, but the current version is here: https://github.com/InovelliUSA/OpenZWave/tree/master/config/inovelli

**Pull request merged**
