### PR TITLE
Update manufacturer_specific.xml

### PR DESCRIPTION
**Pull request by nechry**
content of file swiidinter.xml
```
<?xml version="1.0" encoding="utf-8"?>
<Product xmlns='http://code.google.com/p/open-zwave/'>
<!-- Swiidinter (Z-Wave Cord Switch) -->
	<!-- Configuration -->
	<CommandClass id="112">
		<Value type="list" genre="config" instance="1" index="1" label="Switch All" value="255" size="1">
      <Help>Activate/Deactive ALL ON/OFF</Help>
      <Item label="Disabled" value="0" />
      <Item label="Switch off only" value="1" />
      <Item label="Switch on only" value="2" />
      <Item label="Fully enabled (Default)" value="255" />
    </Value>
</CommandClass>

	<!-- Association Groups -->
	<CommandClass id="133">
		<Associations num_groups="2">
			<Group index="1" max_associations="5" label="Long press" auto="false"/>
			<Group index="2" max_associations="5" label="Short press" auto="true" />			
		</Associations>
	</CommandClass>
</Product>
```

### CODE REVIEW

**Comment by nechry** [comment]
this is the config for SwiidInter base on http://www.swiid.com/fr/support/documentaion-swiidinter.html

**Comment by Fishwaldo** [comment]
you can just "git add swiid/swiidinter.xml" to your branch and push the commit.

**Comment by nechry** [comment]
right, done in https://github.com/OpenZWave/open-zwave/pull/541

**Comment by Fishwaldo** [comment]
thanks. You could have updated your patch-13 branch as well, no need to submit a new PR :)

**Comment by nechry** [comment]
Hello, I just do mistake with this pullRequest... My patch-13 is wrong, I put the decimals values instead of hexa, so the manufacturer id is 166 and device type 100 and id 100.
Do you prefert I close this one and update the other patch? I do to quickly my stuff...

**Comment by Fishwaldo** [comment]
As you discovered you just need to commit to your branch, github will automatically update the PR.

**Pull request merged**
