### PR TITLE
Updated confs from jeedom 1 commit by modification (all config tested and used by jeedom dev team and lots of jeedom users)

### PR DESCRIPTION
**Pull request by sarakha63**
Updated confs from jeedom 1 commit by modification (all config tested and used by jeedom dev team and lots of jeedom users)

### CODE REVIEW

**Comment by Fishwaldo** [comment]
It's going to take me a while to review this.

**Comment by sarakha63** [comment]
Yes from now it will ne more often.

But you can be confindent on the prs. But for sure you must check (of course)

**Comment by Fishwaldo** [comment]
I've merged. But there were lots of XML errors. Some of the configs wouldn't have worked correctly. Please use "make xmltest" when doing new config files in the future. It will validate the config files are correct.

**Comment by sarakha63** [comment]
OK just noticed the modification you made on the octan remote config file

**Pull request merged**
