### PR TITLE
Implemented Command Class "ManufacturerProprietary", merge from Dev

### PR DESCRIPTION
**Pull request by ChristianKuehnel**
For Venetian blind mode of Fibaro FGRM-222 devices

Merging the change from Dev to master: https://github.com/OpenZWave/open-zwave/pull/1204

### CODE REVIEW

**Comment by ChristianKuehnel** [comment]
Just gave it another test run using MinOZW. Still looking good :smile: 

```
2017-11-25 08:59:41.299 Info, Node017, Received Fibaro proprietary blind/slat position for node 17: Blinds: 11 Slats: 19
2017-11-25 08:59:41.299 Detail, Node017, Initial read of value
2017-11-25 08:59:41.299 Detail, Node017, Initial read of value
2017-11-25 08:59:41.299 Detail, Node017, Notification: ValueChanged
2017-11-25 08:59:41.299 Detail, Node017, Notification: ValueChanged
2017-11-25 08:59:41.346 Detail, Node017,   Received: 0x01, 0x0c, 0x00, 0x04, 0x00, 0x11, 0x06, 0x31, 0x05, 0x04, 0x22, 0x00, 0x00, 0xf2
2017-11-25 08:59:41.346 Detail, 
```

**Comment by ChristianKuehnel** [comment]
Hey @nechry 

what do I have to do to get this change merged? Is anything missing?
(It's been sitting for a very long time in the Dev branch...)

And without this change, I cannot merge me change to Home Assistant: https://github.com/ChristianKuehnel/home-assistant/tree/fibaro_tilt

**Comment by Fishwaldo** [comment]
master branch is for bug fixes only. Dev branch is new features etc. So not merging this.

**Comment by ChristianKuehnel** [comment]
HI @Fishwaldo 

And when will the Dev branch be merged?  I provided the patch 6 months ago...

**Pull request closed without merging**
