### PR TITLE
Update manufacturer_specific.xml

### PR DESCRIPTION
**Pull request by ramess18**
Add D-link DCH-Z510 Siren.

### CODE REVIEW

**Comment by gizmocuz** [comment]
Did you forgot to add the dch-z510.xml file ?

**Comment by ramess18** [comment]
Hi. I am adding here. I've made configuration class but I am not able to add associations and others. Could you please help me with it? I added zwcfg.xml and dch-z510.xml in zip.
[z510.zip](https://github.com/OpenZWave/open-zwave/files/93995/z510.zip)
thank you!

**Comment by Fishwaldo** [comment]
Please read https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by Fishwaldo** [comment]
Any update? Otherwise closing this

**Comment by ramess18** [comment]
Hi Fishwaldo, close it. I am not skilled enough to add correct associations. I've hardly made configuration class :(

**Comment by pepeEL** [comment]
Hi
I done it in PR #764

**Pull request closed without merging**
