### PR TITLE
Add central scene support for WA00Z

### PR DESCRIPTION
**Pull request by dhylands**
Added a valueID for each switch. Without this, the button
presses don't get reported.

### CODE REVIEW

**Comment by nechry** [comment]
@dhylands  did you run make xmltest before submit your PR?

**Comment by dhylands** [comment]
I did not. Thanks for pointing that out - I will run it and update appropriatelt,

**Comment by dhylands** [comment]
Ran `make xmltest` and fixed the errors that it detected.

**Comment by Fishwaldo** [comment]
Have you tested this device with the dev branch?

**Comment by dhylands** [comment]
I tested with the latest master. My original testing was done with a device on loan to me and I've returned it. I ordered one and it will show up later this week, at which point I'll retest on the dev branch.

**Comment by dhylands** [comment]
Rebased and tested against Dev branch.
Tweaked the scene count and indentation to be consistent with other devices supporting the CENTRAL_SCENE command class.

**Comment by dhylands** [comment]
Should I also bump the Revision from 1 to 2?

I noticed that when I run make xmltest on the dev branch I'm getting a warning about an md5 mismatch. Is something I need to fix? Or is that managed elsewhere?

I also noticed that my editor used spaces instead of tabs.

Do you want a ChangeLog change included in this PR?

**Comment by dhylands** [comment]
Upped the version from 1 to 2.

**Comment by Fishwaldo** [comment]
Thanks!

**Pull request merged**
