### PR TITLE
Device Support: Nexia DB100Z Z-Wave Doorbell Sensor configuration params

### PR DESCRIPTION
**Pull request by shanemadden**
Add configuration support for the Nexia DB100Z Z-Wave Doorbell Sensor.

It's only got one config param according to http://products.z-wavealliance.org/products/1349/configs, pretty simple/boring. Device works well otherwise - alarm class notifications (class 113, index 11, value of 0/1) for the doorbell state, and battery class for the battery reports, works great after discovery.

### CODE REVIEW

**Comment by Fishwaldo** [comment]
Please add Association Group Info for this device.

**Comment by shanemadden** [comment]
@Fishwaldo All set, sorry about that - I wasn't clear on needing to get the group 1's in there when they were discovered (and handled as auto) properly in the defaults. Thanks a lot!

**Comment by Fishwaldo** [comment]
Its mainly for the Group Names despite the Auto Discovery. And for setting a sane value for auto on each group if needed.

**Comment by shanemadden** [comment]
@Fishwaldo Got it, I'll make sure to get them in there next time I'm adding new devices. Thanks a lot!

**Comment by Fishwaldo** [comment]
Thanks!

**Pull request merged**
