### PR TITLE
Log _instance as well as node for switches and meters (Fix for issue #883)

### PR DESCRIPTION
**Pull request by travellingkiwi**
Add the _instance to the node when logging message regarding switches and meters. This ensures
that we can track which instance of a multi-instance device the message is for

### CODE REVIEW

**Comment by Fishwaldo** [comment]
Hi,
So I see two issues here:
1) Yes - It will break the existing Log Analyzer. I can fix that, but it just takes time..
2) Technically, almost all CC's support MultiInstance, so this need to be universal change... If you can fix this up, I'll try to pull it into the Dev Branch once I got time to also get the Log Analyzer updated. (days/weeks? hopefully not months!)

**Comment by travellingkiwi** [comment]
Sorry, what do you mean by universal change?

**Comment by Fishwaldo** [comment]
All Command Classes, not just the ones you have done so far.... 

If you read though the source of each, you will see those documented that dont' support MulitInstance and can ignore them...

**Comment by travellingkiwi** [comment]
Done. Plus Values so they log correctly as well. e.g.

```
016-05-20 08:01:08.335 Detail, Node010:001, Refreshed Value: old value=false, new value=false, type=bool
2016-05-20 08:01:08.335 Detail, Node010:001, Changes to this value are not verified
2016-05-20 08:01:08.335 Info, Node010:001, Received Meter report from node 10: Power=0.7W
2016-05-20 08:01:08.335 Detail, Node010:001, Refreshed Value: old value=0.8, new value=0.7, type=decimal
2016-05-20 08:01:08.335 Detail, Node010:001, Changes to this value are not verified

```

**Comment by Fishwaldo** [comment]
Thanks... will merge soon once i update the Log Analyzer (which should be simple)

**Comment by Fishwaldo** [comment]
Hi,
Apologies, I just cleaned up the repo, removing old object files from way back when. This has resulted in PR's being messed up. Could you please redo the PR after pulling a new fork (the repo should be much smaller now though)

Thanks

**Pull request closed without merging**
