### PR TITLE
add new ct80 product type and id

### PR DESCRIPTION
**Pull request by chilicheech**
This is identical to 00711e8a107c93c90d18e2e77fcfd38833372c2e but I'm using the Dev branch so I need it here :)

Cheers,

### CODE REVIEW

**Comment by nechry** [comment]
Config in dev branch will perform soon.

**Comment by nechry** [comment]
This PR target the dev branch, @Fis

**Comment by chilicheech** [comment]
Yes, just like #1440 .. Why is this one tagged as not ready?

**Comment by chilicheech** [comment]
@nechry @Fishwaldo any updates on this?

**Comment by chilicheech** [comment]
This code is in Dev already. Closing this PR.

**Pull request closed without merging**
