### PR TITLE
ZHC5010 Fix CentralScene support

### PR DESCRIPTION
**Pull request by philipsoeberg**
CentralScene is issued from Root device endpoint0 which by default maps to instance0, but all CCs start from instance1.
Map endpoint0 to instance1.

### CODE REVIEW

**Comment by philipsoeberg** [comment]
Debugging an issue where no ValueID is present after Join of new node...

**Comment by philipsoeberg** [comment]
Errorcode 40, had resat CentralScene.cpp back to Master. Damn. Ah well, better be safe and recheck when things break. This xml addition is valid.

**Comment by Fishwaldo** [comment]
CentralScene isn't working in Master - How are you testing this?

**Comment by philipsoeberg** [comment]
Hi Fishwaldo,

I simply cherry picked CenstralScene.cpp and CentralScene.h from Dev branch, with no changes, straight into Master to get it working. My diff is here: https://github.com/philipsoeberg/open-zwave/commit/1e8f09c5c56cd10462a5f35811c108f5ed43ca70

The XML change doesn't hurt if CentralScene is not active but it is needed if CenstralScene support is included.

**Comment by JonasPed** [comment]
I can confirm that this fix works.

**Comment by AlCalzone** [comment]
Well, this sounds a lot like my issue here: https://github.com/OpenZWave/open-zwave/issues/1171
I might give that a try until CS support gets officially merged.

**Pull request closed without merging**
