### PR TITLE
Update Neo CoolCam NAS-WR01ZE

### PR DESCRIPTION
**Pull request by Beddie**
Update Neo CoolCam NAS-WR01ZE based on newly created shenzen_neo config: "nas-wr01ze.xml"

### CODE REVIEW

**Comment by nechry** [comment]
@Beddie please provide the nas-wr01ze.xml file

**Comment by Beddie** [comment]
@nechry Please look at https://github.com/Beddie/open-zwave/blob/patch-1/config/shenzen_neo/nas-wr01ze.xml

**Comment by Beddie** [comment]
@nechry Please look at pull request https://github.com/OpenZWave/open-zwave/pull/1723

**Comment by Peboli** [comment]
@nechry, thanks for closing #1726 , I saw the pull request afterwards.
What about inclusion in secured mode (S2) does it need special settings in config file ?

**Comment by nechry** [comment]
@Beddie I also notified, this is not really pertinent.

**Comment by nechry** [comment]
@Peboli openzwave does not support S2 for the moment. Any help will be appreciated

**Comment by nechry** [comment]
thank @Beddie

**Pull request merged**
