### PR TITLE
add leviton dzpa1

### PR DESCRIPTION
**Pull request by techgaun**
This is the device: http://products.z-wavealliance.org/products/1959. The config params and association groups match with https://github.com/OpenZWave/open-zwave/blob/master/config/leviton/dz15s.xml so just using that

### CODE REVIEW

**Comment by nechry** [comment]
exlude the distfiles.mk file and please add your leviton/dz15s.xml file. we can close the PR and create a new one insted

**Comment by techgaun** [comment]
@nechry hi thanks for reviewing it. I updated this PR to include that change only. The dz15s.xml file is already there: https://github.com/OpenZWave/open-zwave/blob/master/config/leviton/dz15s.xml and it uses the same config parameters.. Do I need to copy that xml file and create a separate one?

**Comment by nechry** [comment]
ok sorry I did't realise

**Comment by techgaun** [comment]
thanks!

**Pull request merged**
