### PR TITLE
Create MHP220.xml

### PR DESCRIPTION
**Pull request by tonbor**

### CODE REVIEW

**Comment by tonbor** [comment]
MCOhome MH-P220 mini dimmer ZWAVE plus
<Manufacturer id="015f" name="McoHome Technology Co Ltd">
    <Product id="0001" name="Mini Energy Dimmer" type="0001"/>
    <Product id="0001" name="Mini Energy Switch" type="0002"/>
    
    <Product config="mcohome/mhp210.xml" id="1302" name="MH-P210 Mini Energy Dimmer" type="210a"/>
    <Product config="mcohome/mhp220.xml" id="5102" name="MH-P220 Mini Energy Dimmer" type="220a"/>
    <Product config="mcohome/mhs311.xml" id="0201" name="MH-S311 One-load" type="3102"/>
    <Product config="mcohome/mhs312.xml" id="0202" name="MH-S312 Two-load" type="3102"/>
    <Product config="mcohome/mhs314.xml" id="0204" name="MH-S314 Four-load" type="3102"/>
    <Product config="mcohome/mhs314.xml" id="1302" name="MH-S314 Four-load" type="3141"/>
    <Product config="mcohome/mhs314.xml" id="3141" name="MH-S314 Four-load" type="5102"/>
    <Product config="mcohome/mhs411.xml" id="0201" name="MH-S411 One-load" type="4102"/>
    <Product config="mcohome/mhs412.xml" id="0202" name="MH-S412 Two-load" type="4102"/>
    <Product config="mcohome/mhs412.xml" id="1302" name="MH-S412 Two-load" type="4121"/>
    <Product config="mcohome/mhs412.xml" id="5102" name="MH-S412 Two-load" type="4121"/>
    <Product config="mcohome/mh8fceu.xml" id="3102" name="MH8-FC-EU Thermostat" type="0801"/>
    <Product config="mcohome/mh8fceu.xml" id="3102" name="MH8-FC4-EU Thermostat" type="0802"/>
    <Product config="mcohome/mh9co2.xml" id="0201" name="MH9-CO2-WD CO2 Monitor" type="0905"/>
    <Product config="mcohome/mh9co2.xml" id="3102" name="MH9-CO2-WD CO2 Monitor" type="0901"/>
    <Product config="mcohome/a8-9.xml" id="1352" name="A8-9 Multi-sensor" type="a800"/>
    <Product config="mcohome/mh7h.xml" id="5102" name="MH7H Water/Electrical Heating Thermostat" type="0701"/>
    <Product config="mcohome/mh7h.xml" id="5102" name="MH7H Water/Electrical Heating Thermostat" type="0702"/>
    <Product config="mcohome/mh7h.xml" id="5102" name="MH7H Water/Electrical Heating Thermostat" type="0712"/>
    <Product config="mcohome/mh7h.xml" id="5102" name="MH7H Water/Electrical Heating Thermostat" type="0732"/>
    
    <Product config="mcohome/mhs513.xml" id="0103" name="Touch Panel Switch MH-S513" type="5102"/>
  </Manufacturer>

**Comment by tonbor** [comment]
<Manufacturer id="015f" name="McoHome Technology Co Ltd">
    <Product id="0001" name="Mini Energy Dimmer" type="0001"/>
    <Product id="0001" name="Mini Energy Switch" type="0002"/>
    
    <Product config="mcohome/mhp210.xml" id="1302" name="MH-P210 Mini Energy Dimmer" type="210a"/>
    <Product config="mcohome/mhp220.xml" id="5102" name="MH-P220 Mini Energy Dimmer" type="220a"/>
    <Product config="mcohome/mhs311.xml" id="0201" name="MH-S311 One-load" type="3102"/>
    <Product config="mcohome/mhs312.xml" id="0202" name="MH-S312 Two-load" type="3102"/>
    <Product config="mcohome/mhs314.xml" id="0204" name="MH-S314 Four-load" type="3102"/>
    <Product config="mcohome/mhs314.xml" id="1302" name="MH-S314 Four-load" type="3141"/>
    <Product config="mcohome/mhs314.xml" id="3141" name="MH-S314 Four-load" type="5102"/>
    <Product config="mcohome/mhs411.xml" id="0201" name="MH-S411 One-load" type="4102"/>
    <Product config="mcohome/mhs412.xml" id="0202" name="MH-S412 Two-load" type="4102"/>
    <Product config="mcohome/mhs412.xml" id="1302" name="MH-S412 Two-load" type="4121"/>
    <Product config="mcohome/mhs412.xml" id="5102" name="MH-S412 Two-load" type="4121"/>
    <Product config="mcohome/mh8fceu.xml" id="3102" name="MH8-FC-EU Thermostat" type="0801"/>
    <Product config="mcohome/mh8fceu.xml" id="3102" name="MH8-FC4-EU Thermostat" type="0802"/>
    <Product config="mcohome/mh9co2.xml" id="0201" name="MH9-CO2-WD CO2 Monitor" type="0905"/>
    <Product config="mcohome/mh9co2.xml" id="3102" name="MH9-CO2-WD CO2 Monitor" type="0901"/>
    <Product config="mcohome/a8-9.xml" id="1352" name="A8-9 Multi-sensor" type="a800"/>
    <Product config="mcohome/mh7h.xml" id="5102" name="MH7H Water/Electrical Heating Thermostat" type="0701"/>
    <Product config="mcohome/mh7h.xml" id="5102" name="MH7H Water/Electrical Heating Thermostat" type="0702"/>
    <Product config="mcohome/mh7h.xml" id="5102" name="MH7H Water/Electrical Heating Thermostat" type="0712"/>
    <Product config="mcohome/mh7h.xml" id="5102" name="MH7H Water/Electrical Heating Thermostat" type="0732"/>
    
    <Product config="mcohome/mhs513.xml" id="0103" name="Touch Panel Switch MH-S513" type="5102"/>
  </Manufacturer>

**Comment by tonbor** [comment]
<Product config="mcohome/mhp220.xml" id="5102" name="MH-P220 Mini Energy Dimmer" type="220a"/>

Manufacturer ID: | 015f
-- | --
Manufacturer: | Mcohome
Product: | Micro Dimmer
Product ID: | 0x5101
Product Type: | 0x220A

<?xml version="1.0" encoding="UTF-8"?>

-<ProductExport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<Id>3011</Id>

<Name> Micro Dimmer</Name>

<Description>This in-wall module is with compact design as well as stable performance, which can suit for any of the installation box and various operation situation. It supports basic command class, and also can act as repeater regardless of vendor to increase reliability of the network.</Description>

<Description_Short>Micro Dimmer is a Z-Wave Plus enabled in-wall module which can be wired with a wall switch panel for dimming purpose. </Description_Short>

<Brand>MCO Home</Brand>

<Identifier> MH-P220</Identifier>

<CertificationNumber>ZC10-18086201</CertificationNumber>

<OemVersion>HW: 255 FW: 3.02</OemVersion>

<HardwarePlatform>ZM5202</HardwarePlatform>

<ZWaveVersion>6.71.03</ZWaveVersion>

<LibraryType>Enhanced 232 Slave</LibraryType>

<DeviceType>Light Dimmer Switch</DeviceType>

<RoleType>Always On Slave</RoleType>

<ManufacturerId>0x015F</ManufacturerId>

<ProductTypeId>0x220A</ProductTypeId>

<ProductId>0x5101</ProductId>

**Comment by tonbor** [comment]
Please add to OZW config xml

**Comment by tonbor** [comment]
I have added discription

**Comment by petergebruers** [comment]
Hi! Thank you for your submission. To add files a few steps have to be taken, please have a look at the instructions here:

https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

Please give it a try... If you'r still still stuck after that, I'll give you a hand...

**Comment by tonbor** [comment]
You not a line for the manufactory XML, you not the whole working config
xml, you not a discription of the device you got a link to the
certificering. Sp no ideas what you neer more.

Regards

Rob Gloudi

Op wo 10 jul. 2019 13:46 schreef Peter Gebruers <notifications@github.com>:

**Comment by petergebruers** [comment]
I understand that the "wiki" page is long and you might not have seen what 

One of the things you need to do is run this test:

make xmltest

It will tell you if everything is OK or if some things need to change

**Comment by petergebruers** [comment]
By the way, I am quite sure some things are not OK because of this text (see above) "Some checks have failed"

**Comment by tonbor** [comment]
Well, it is working ok with me checked the XML on a XML checker at the
internet  and most off the XML comes from cd-jackson openhab. But i will
check......

Op wo 10 jul. 2019 15:20 schreef Peter Gebruers <notifications@github.com>:

**Comment by petergebruers** [comment]
Sure, that is a good start but "make xmltest" does more than that, for instance, it checks "revision numbers" and online xml checks don't do that.

If you are stuck I will have a look but I am not at home today, so cannot do that right now.

**Comment by Fishwaldo** [comment]
This is a config file for version 1.4 of OZW. We are now at version 1.6 so it needs to be updated for the latest version. 

And there is no entry in manufacture_specific.xml so it won’t do anything.

**Comment by petergebruers** [comment]
As @Fishwaldo points out... There's more work to do, and as I've said, detailed instructions are here

https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by tonbor** [comment]
What error do you get, me none…

 

And what do I have to change for 1.4 to 1.6……. I am just a customer who wants to use it z-wave switch not a developer , I got this from openhab and adjusted it so it fits ozw form

 

Regards,

 

Rob Gloudi

 

 

 

 

XML Validator - check well-formedness W3C XML 1.0 specifications, validate against schema xsd 

1

2<Product xmlns="http://code.google.com/p/open-zwave/">



3          

4          

5       <CommandClass id="112">



6              <Value type="byte" size="1" value="1" max="1" min="0" units="
" label="Dimmer state after power down" index="1" instance="1" genre="config">



7                     <Help>Dimmer state saved or not when power down</Help>

8                 </Value>

9              <Value type="byte" size="1" value="0" max="2" min="0" units="
" label="External switch type" index="2" instance="1" genre="config">



10                     <Help>External switch type</Help>

11                 </Value>

12              <Value type="byte" size="1" value="1" max="1" min="0" units="
" label="2-state Switches" index="3" instance="1" genre="config">



13                     <Help>2-state Switches</Help>

14                 </Value>

15              <Value type="byte" size="1" value="255" max="255" min="0" units="
" label="ALL ON/ALL OFF" index="4" instance="1" genre="config">



16                     <Help>ALL ON/ALL OFF</Help>

17                 </Value>

18              <Value type="byte" size="1" value="1" max="98" min="1" units="
" label="Minimum brightness level" index="5" instance="1" genre="config">



19                     <Help>Minimum brightness level</Help>

20                 </Value>

21              <Value type="byte" size="1" value="99" max="99" min="2" units="
" label="Maximum brightness level" index="6" instance="1" genre="config">



22                     <Help>Maximum brightness level</Help>

23                 </Value>

24              <Value type="short" size="2" value="3" max="255" min="1" units="
" label="Single dimming step time(Manual)" index="7" instance="1" genre="config">



25                     <Help>Single dimming step time(Manual)</Help>

26                 </Value>

27              <Value type="byte" size="1" value="1" max="99" min="1" units="
" label="Single dimming step size (Manual)" index="8" instance="1" genre="config">



28                     <Help>Single dimming step size (Manual)</Help>

29                 </Value>

30              <Value type="short" size="2" value="3" max="255" min="1" units="
" label="Single dimming step time (Auto)" index="9" instance="1" genre="config">



31                     <Help>Single dimming step time (Auto)</Help>

32                 </Value>

33              <Value type="byte" size="1" value="1" max="99" min="1" units="
" label="Single dimming step size (Auto)" index="10" instance="1" genre="config">



34                     <Help>Single dimming step size (Auto)</Help>

35                 </Value>

36              <Value type="short" size="2" value="0" max="255" min="0" units="
" label="Timer function (Auto-off)" index="11" instance="1" genre="config">



37                     <Help>Timer function (Auto-off)</Help>

38                 </Value>

39              <Value type="byte" size="1" value="99" max="99" min="0" units="
" label="One click of S1" index="13" instance="1" genre="config">



40                     <Help>One click of S1</Help>

41                 </Value>

42              <Value type="byte" size="1" value="1" max="1" min="0" units="
" label="Double click of S1" index="14" instance="1" genre="config">



43                     <Help>Double click of S1</Help>

44                 </Value>

45              <Value type="byte" size="1" value="0" max="255" min="0" units="
" label="Operation report Switch1 to Assoc Group 2 and 3" index="15" instance="1" genre="config">



46                     <Help>Operation report from Switch1 to Association Group 2 and 3</Help>

47                 </Value>

48              <Value type="byte" size="1" value="1" max="1" min="0" units="
" label="Operation report Switch1 to Association Group 2" index="16" instance="1" genre="config">



49                     <Help>Operation report from Switch1 to Association Group 2</Help>

50                 </Value>

51              <Value type="byte" size="1" value="1" max="255" min="0" units="
" label="Switch 2 function" index="17" instance="1" genre="config">



52                     <Help>Switch 2 function</Help>

53                 </Value>

54              <Value type="byte" size="1" value="0" max="255" min="0" units="
" label="Operation report Switch2 to Association Group 4" index="18" instance="1" genre="config">



55                     <Help>Operation report from Switch2 to Association Group 4</Help>

56                 </Value>

57              <Value type="byte" size="1" value="0" max="255" min="0" units="
" label="Scene ID sent to AG1 when one click of S2" index="19" instance="1" genre="config">



58                     <Help>Scene ID sent to AG1 when one click of S2</Help>

59                 </Value>

60              <Value type="byte" size="1" value="0" max="255" min="0" units="
" label="Scene ID sent to AG1 double click of S2" index="20" instance="1" genre="config">



61                     <Help>Scene ID sent to AG1 when double click of S2</Help>

62                 </Value>

63              <Value type="byte" size="1" value="0" max="255" min="0" units="
" label="Scene ID sent to AG1 when hold S2" index="21" instance="1" genre="config">



64                     <Help>Scene ID sent to AG1 when hold S2</Help>

65                 </Value>

66          </CommandClass>

67          

68       <CommandClass id="133">



69              <Associations num_groups="4">



70                     <Group label="Lifeline" index="1" auto="true" max_associations="1">
</Group>

71                     <Group label="Basic Set Command S1" index="2" max_associations="5">
</Group>

72                     <Group label="Multi-level Set Command" index="3" max_associations="5">
</Group>

73                     <Group label="Basic Set Command S2" index="4" max_associations="5">
</Group>

74                 </Associations>

75          </CommandClass>

76   </Product>

This document was successfully checked as well-formed XML!

 

How To Validate XML Documents? 

*	Load XML data. You can choose one of the three ways to load your XML data;
*	Your XML data will be first checked against W3C XML 1.0 specifications for well-formedness;
*	If any syntax error is found, you will see the error message about the error, correct the error in the source box and click the Check Syntax button to check it again;
*	After no syntax error is found in the XML, you can validate it against the associated schema XSD, click the Validate button;

 

 

Van: Peter Gebruers [mailto:notifications@github.com] 
Verzonden: woensdag 10 juli 2019 16:07
Aan: OpenZWave/open-zwave <open-zwave@noreply.github.com>
CC: tonbor <rob.gloudi@gmail.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [OpenZWave/open-zwave] Create MHP220.xml (#1853)

 

Sure, that is a good start but "make xmltest" does more than that, for instance, it checks "revision numbers" and online xml checks don't do that.

If you are stuck I will have a look but I am not at home today, so cannot do that right now.

**Comment by tonbor** [comment]
I submitted the line for manufacture_specific.xml too…….

 

Van: Justin Hammond [mailto:notifications@github.com] 
Verzonden: woensdag 10 juli 2019 16:11
Aan: OpenZWave/open-zwave <open-zwave@noreply.github.com>
CC: tonbor <rob.gloudi@gmail.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [OpenZWave/open-zwave] Create MHP220.xml (#1853)

 

This is a config file for version 1.4 of OZW. We are now at version 1.6 so it needs to be updated for the latest version.

And there is no entry in manufacture_specific.xml so it won’t do anything.

**Comment by petergebruers** [comment]
@tonbor, you say "I submitted the line for manufacture_specific.xml too" but if you click on "changes" you will see this PR does not have that file... Maybe it exists on your PC and you forgot to push your changes?

**Comment by petergebruers** [comment]
Ah! I think I understand why you are confused about "make xmltest"! You say you are not a developer, so you probaply have never built OpenZWave from source. "make" is a special tool to build this project, it is used on Mac and Linux. This "make xmltest" is a command you run in a terminal or "shell"... It does a lot more than online xml checkers!

But that's OK, not everybody has to be a developer.

Because "github" is a developer tool we kind of assume you've build from source...

Anyway.

Your file is missing data, that is what @Fiswaldo means when he says "it is not a 1.6 file". You can add the missing bits. You do not have to do this, but it would be a great help...

To avoid further confusion, you say "this file works" so I wonder what gateway software do you use? Is it "Home Assistant"? It is important to know, because config files for an older version of OpenZWave are not compatible.

**Comment by tonbor** [comment]
Domoticz with openzwave 1.6, and I did not try to change all parameters but
the one I changed worked.



Op wo 10 jul. 2019 16:58 schreef Peter Gebruers <notifications@github.com>:

**Comment by petergebruers** [comment]
That's good. I'll try to have a look at this today.

**Comment by tonbor** [comment]
Sorry, id-5101 is old data, the right id is 5102 (or 1352) NOT 5101. 

<ManufacturerSpecificData>
  <Manufacturer id="015f" name="McoHome Technology Co., Ltd">
    <Product type="220a" id="1352" name="MH-P220" config="xxxxxxx"/>
    <Product type="220a" id="5102" name="MH-P220" config="xxxxxxx"/>
  </Manufacturer>
</ManufacturerSpecificData>

**Comment by tonbor** [comment]
<ManufacturerSpecificData>
  <Manufacturer id="015f" name="McoHome Technology Co., Ltd">
    <Product type="220a" id="1352" name="MH-P220" config="xxxxxxx"/>
    <Product type="220a" id="5102" name="MH-P220" config="xxxxxxx"/>
  </Manufacturer>
</ManufacturerSpecificData>

**Pull request merged**
