### PR TITLE
ZME_064281 Wall Plug switch Schuko (IP44) - Gen 5

### PR DESCRIPTION
**Pull request by digdug3**
Add support for the ZME_064281 Wall Plug switch Schuko (IP44) - Gen 5 based on hellqvist PPOP device. (Same device, different manufacturer)

### CODE REVIEW

**Comment by Fishwaldo** [comment]
I added this already based on the mailing list message. But thanks anyway.

**Comment by digdug3** [comment]
Somehow this device got removed? Could you please merge again?

**Comment by nechry** [comment]
https://github.com/digdug3/open-zwave/blob/master/config/manufacturer_specific.xml#L781
Is there or I mist something?

**Comment by nechry** [comment]
Ha the zwave.me/ZME_064381.xml is missing. I will check this soon

**Pull request closed without merging**
