### PR TITLE
Create ses5g.xml

### PR DESCRIPTION
**Pull request by nechry**
is a configuration file for Aeon Labs Smart Switch Gen5 base on 
http://ozw.my-ho.st/Aeon/Engineering%20Spec%20-%20Aeon%20Labs%20Smart%20Switch%20Gen5_V3.25.pdf
specification

But I did not received the device so I don't have the type and id right now to complete the manufacturer_specific.xml
<Product type="" id="" name="Smart Switch Gen5" config="aeon_labs/ses5g.xml" />

### CODE REVIEW

**Comment by Fishwaldo** [comment]
No rush to add any Gen5 gear at the moment because it's broken. I'll pull this into the Security Rewrite branch instead soon.

**Comment by nechry** [comment]
I expect receive my order next week. I will update the manufacturer_specific.xml at this time. But yes no rush.

**Comment by strips** [comment]
Maybe no rush for you :D Hehe.

I for one am VERY eagerly waiting for Gen5 support as I have only bought gen5 stuff as my first trial of z-wave. I'm close to ordering a Vera Edge as alternative but would very much like to test Domoticz first.

**Comment by strips** [comment]
@Fishwaldo 

If the security rewrite will enable Aeon Labs Gen5 stuff I wouldn't mind help testing the gen5 stuff. I dont have any security devices but am currently testing a Aeon Labs Multisensor Gen5 and AEON gen5 Switch. None work as they should. They work fine in Homeseer and inControl.

**Comment by Fishwaldo** [comment]
You in fact do have a Security Device. All the Gen5 gear supports the Security CC. The difference is that the Gen5 stuff makes it optional over other devices (which the Security CC was written again) where its mandatory. 

You can track the development in the Issue-352 branch... But its no where near ready for outside testing yet. 

Anyway, Aeon Labs were kind enough to send me all their Gen5 stuff, so watch the commits and mailing lists and you should see when its ready for some "beta" testing... (a few weeks I'd estimate given my current real life workload)

**Comment by tmartinez69009** [comment]
Hello, 
For info, i have the 2 usb sticks aeotec GEN5 (ZStick Gen5 & ZStick Lite Gen5) for testing (developper preview models) and they are working very well with OpenZwave !

**Comment by nechry** [comment]
so I confirm, the discovering stock on SecurityReport, I don't have any device id and type yet. wait and see for any progress with this securityClass also available for testing.

is my xml node:

<Node id="64" name="" location="" basic="4" generic="16" specific="1" type="Binary Power Switch" listening="true" frequentListening="false" beaming="true" routing="true" max_baud_rate="40000" version="4" query_stage="SecurityReport">
		<Manufacturer id="" name="">
			<Product type="" id="" name="" />
		</Manufacturer>
		<CommandClasses>
			<CommandClass id="32" name="COMMAND_CLASS_BASIC" version="1" request_flags="4" mapping="37">
				<Instance index="1" />
			</CommandClass>
			<CommandClass id="37" name="COMMAND_CLASS_SWITCH_BINARY" version="1" request_flags="4">
				<Instance index="1" />
				<Value type="bool" genre="user" instance="1" index="0" label="Switch" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
			</CommandClass>
			<CommandClass id="39" name="COMMAND_CLASS_SWITCH_ALL" version="1" request_flags="4">
				<Instance index="1" />
				<Value type="list" genre="system" instance="1" index="0" label="Switch All" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" vindex="0" size="1">
					<Item label="Disabled" value="0" />
					<Item label="Off Enabled" value="1" />
					<Item label="On Enabled" value="2" />
					<Item label="On and Off Enabled" value="255" />
				</Value>
			</CommandClass>
			<CommandClass id="43" name="COMMAND_CLASS_SCENE_ACTIVATION" version="1" request_flags="4">
				<Instance index="1" />
			</CommandClass>
			<CommandClass id="50" name="COMMAND_CLASS_METER" version="1" request_flags="6">
				<Instance index="1" />
				<Value type="decimal" genre="user" instance="1" index="0" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
			</CommandClass>
			<CommandClass id="86" name="COMMAND_CLASS_CRC_16_ENCAP" version="1" request_flags="4">
				<Instance index="1" />
			</CommandClass>
			<CommandClass id="112" name="COMMAND_CLASS_CONFIGURATION" version="1" request_flags="4">
				<Instance index="1" />
			</CommandClass>
			<CommandClass id="114" name="COMMAND_CLASS_MANUFACTURER_SPECIFIC" version="1" request_flags="6">
				<Instance index="1" />
			</CommandClass>
			<CommandClass id="115" name="COMMAND_CLASS_POWERLEVEL" version="1" request_flags="4">
				<Instance index="1" />
				<Value type="list" genre="system" instance="1" index="0" label="Powerlevel" units="dB" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" vindex="0" size="1">
					<Item label="Normal" value="0" />
					<Item label="-1dB" value="1" />
					<Item label="-2dB" value="2" />
					<Item label="-3dB" value="3" />
					<Item label="-4dB" value="4" />
					<Item label="-5dB" value="5" />
					<Item label="-6dB" value="6" />
					<Item label="-7dB" value="7" />
					<Item label="-8dB" value="8" />
					<Item label="-9dB" value="9" />
				</Value>
				<Value type="byte" genre="system" instance="1" index="1" label="Timeout" units="seconds" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="0" />
				<Value type="button" genre="system" instance="1" index="2" label="Set Powerlevel" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
				<Value type="byte" genre="system" instance="1" index="3" label="Test Node" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="0" />
				<Value type="list" genre="system" instance="1" index="4" label="Test Powerlevel" units="dB" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" vindex="0" size="1">
					<Item label="Normal" value="0" />
					<Item label="-1dB" value="1" />
					<Item label="-2dB" value="2" />
					<Item label="-3dB" value="3" />
					<Item label="-4dB" value="4" />
					<Item label="-5dB" value="5" />
					<Item label="-6dB" value="6" />
					<Item label="-7dB" value="7" />
					<Item label="-8dB" value="8" />
					<Item label="-9dB" value="9" />
				</Value>
				<Value type="byte" genre="system" instance="1" index="5" label="Frame Count" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="-32768" max="32767" value="0" />
				<Value type="button" genre="system" instance="1" index="6" label="Test" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
				<Value type="button" genre="system" instance="1" index="7" label="Report" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
				<Value type="list" genre="system" instance="1" index="8" label="Test Status" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" vindex="0" size="1">
					<Item label="Failed" value="0" />
					<Item label="Success" value="1" />
					<Item label="In Progress" value="2" />
				</Value>
				<Value type="byte" genre="system" instance="1" index="9" label="Acked Frames" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-32768" max="32767" value="0" />
			</CommandClass>
			<CommandClass id="130" name="COMMAND_CLASS_HAIL" version="1" request_flags="4" after_mark="true">
				<Instance index="1" />
			</CommandClass>
			<CommandClass id="133" name="COMMAND_CLASS_ASSOCIATION" version="1" request_flags="6">
				<Instance index="1" />
				<Associations num_groups="0" />
			</CommandClass>
			<CommandClass id="134" name="COMMAND_CLASS_VERSION" version="1" request_flags="6">
				<Instance index="1" />
				<Value type="string" genre="system" instance="1" index="0" label="Library Version" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="Unknown" />
				<Value type="string" genre="system" instance="1" index="1" label="Protocol Version" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="Unknown" />
				<Value type="string" genre="system" instance="1" index="2" label="Application Version" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="Unknown" />
			</CommandClass>
			<CommandClass id="152" name="COMMAND_CLASS_SECURITY" version="1" request_flags="4">
				<Instance index="1" />
				<Value type="bool" genre="system" instance="1" index="0" label="Secured" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
			</CommandClass>
		</CommandClasses>
	</Node>

**Comment by Fishwaldo** [comment]
I'm doing the development with a smart switch already. It was already picked up and uses the existing ses2.xml file which was mostly correct. 

I had a quick look at your version, and I think the only thing you had wrong was the association groups. There is only 2 groups but the tech manual is a bit vague on it, so I understand how you got three. 

Also, seeing the "effect" of zwave plus enhancements on these devices. Group 1 is commonly known as lifeline group now, and it will send a NIF packet plus a command class report/set to group 1. The problem is this device sends either a Basic Set or a hail message.  Basic set isn't too bad as it's a listening device. Hail means refresh everything, but in OZW if we receive a NIF packet we already do that. 

Group 2 should send the normal CC reports but I've yet too see it do that. 

It looks like the Aeon Labs Gen5 stuff is going to take a bit more than just refactoring Security. 

The good news is:
1) the Gen5 stuff is fast. With the locks I'd been working with previously you would see latency of over 1 second per encrypted packet. The Aeon Labs stuff is almost instant. 
2) the security branch is mostly working with it. There are still a few things left to be done and I'm still seeing a issue with overlapping NONCE messages that I need to sort out. 
3) I think we have nailed the timeout challenges we were seeing before as we are now doing the inclusion right after the stick reports it found a new node ( we get a "extended NIF" packet that contains all the CC's during inclusion so no need to wait till we get through the querystages) 
4) we can work unencrypted with these devices, but some CC's might be unavailable. So far nothing that breaks core functionality. 

The bad news:
1) new API calls for adding Nodes. 
2) if you wipe zwcfg_*.xml, on restart we will get a timeout when the Security CC probes for supported CC's on devices that were never included securely. 
3) this is going to need a bucket load of testing before I consider it stable. There are a lot of changes in the transaction handling code, some of which I don't understand so I'm hoping I got it right. 

In a few more days I should get it to a stage where I can invite people to test

**Comment by nechry** [comment]
Thank for the update, yes, I thing the doc is not fully right, the association section talk about 2 groups and in parameters I see this one:
0x67 (103)  Which reports need to send in Report group 3
The release before have 3 groups, me be is something wrong in documentations.

They will be need lots of try, I will check also if i can got answer from Aeon Labs

**Comment by Fishwaldo** [comment]
I'm not going to pull this as I've already updated the in the Security Branch.

**Comment by nechry** [comment]
hello, I got a email form aeon-lab and they confirm only 2 associations group. 
"An engineer has told me that the SSGen5 supports 2 association groups."

**Comment by nechry** [comment]
I try to add the controller to group 2 but is not work, is the log:

2015-04-23 20:11:29.192 Info, Node068, Association::Set - Adding node 1 to group 2 of node 68
2015-04-23 20:11:29.192 Detail, Node068, Encrypting Message For Command Class COMMAND_CLASS_ASSOCIATION
2015-04-23 20:11:29.193 Detail, Node068, Queuing (Security) SecurityCmd_NonceGet (Node=68): 0x01, 0x09, 0x00, 0x13, 0x44, 0x02, 0x98, 0x40, 0x05, 0xad, 0xd3
2015-04-23 20:11:29.193 Info, Node068, Get Associations for group 2 of node 68
2015-04-23 20:11:29.193 Detail, Node068, Encrypting Message For Command Class COMMAND_CLASS_ASSOCIATION
2015-04-23 20:11:29.194 Detail, 
2015-04-23 20:11:29.195 Info, Node068, Sending (Security) message (Callback ID=0xad, Expected Reply=0x04) - SecurityCmd_NonceGet (Node=68): 0x01, 0x09, 0x00, 0x13, 0x44, 0x02, 0x98, 0x40, 0x05, 0xad, 0xd3
2015-04-23 20:11:29.203 Detail, Node068,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
2015-04-23 20:11:29.203 Detail, Node068,   ZW_SEND_DATA delivered to Z-Wave stack
2015-04-23 20:11:29.218 Detail, Node068,   Received: 0x01, 0x05, 0x00, 0x13, 0xad, 0x00, 0x44
2015-04-23 20:11:29.219 Detail, Node068,   ZW_SEND_DATA Request with callback ID 0xad received (expected 0xad)
2015-04-23 20:11:29.219 Info, Node068, Request RTT 21 Average Request RTT 26
2015-04-23 20:11:29.231 Detail, Node068,   Received: 0x01, 0x10, 0x00, 0x04, 0x00, 0x44, 0x0a, 0x98, 0x80, 0x7a, 0xc2, 0x2d, 0x90, 0x60, 0xf1, 0xd5, 0xfa, 0x06
2015-04-23 20:11:29.232 Detail, 
2015-04-23 20:11:29.232 Info, Node068, Response RTT 35 Average Response RTT 42
2015-04-23 20:11:29.232 Info, Node068, Received SecurityCmd_NonceReport from node 68
2015-04-23 20:11:29.233 Info, Input Packet: Packet: 0x00, 0x85, 0x01, 0x02, 0x01
2015-04-23 20:11:29.233 Detail, Node068, Queuing (Security) SecurityCmd_MessageEncap (AssociationCmd_Set) (Node=68): 0x01, 0x1f, 0x00, 0x13, 0x44, 0x18, 0x98, 0x81, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x25, 0x19, 0xc7, 0xda, 0x1e, 0x7a, 0xda, 0x5b, 0x41, 0x2a, 0x0f, 0xea, 0x87, 0xdd, 0x25, 0xaf, 0x2c
2015-04-23 20:11:29.234 Detail, Node068,   Expected reply and command class was received
2015-04-23 20:11:29.234 Detail, Node068,   Message transaction complete
2015-04-23 20:11:29.235 Detail, 
2015-04-23 20:11:29.235 Detail, Node068, Removing current message
2015-04-23 20:11:29.236 Detail, 
2015-04-23 20:11:29.236 Info, Node068, Sending (Security) message (Callback ID=0xaf, Expected Reply=0x04) - SecurityCmd_MessageEncap (AssociationCmd_Set) (Node=68): 0x01, 0x1f, 0x00, 0x13, 0x44, 0x18, 0x98, 0x81, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x25, 0x19, 0xc7, 0xda, 0x1e, 0x7a, 0xda, 0x5b, 0x41, 0x2a, 0x0f, 0xea, 0x87, 0xdd, 0x25, 0xaf, 0x2c
2015-04-23 20:11:29.245 Detail, Node068,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
2015-04-23 20:11:29.245 Detail, Node068,   ZW_SEND_DATA delivered to Z-Wave stack
2015-04-23 20:11:29.265 Detail, Node068,   Received: 0x01, 0x05, 0x00, 0x13, 0xaf, 0x00, 0x46
2015-04-23 20:11:29.266 Detail, Node068,   ZW_SEND_DATA Request with callback ID 0xaf received (expected 0xaf)
2015-04-23 20:11:29.267 Info, Node068, Request RTT 29 Average Request RTT 27
2015-04-23 20:11:35.237 Detail, 
2015-04-23 20:11:35.238 Info, Node068, Sending (Security) message (Attempt 2, Callback ID=0xb0, Expected Reply=0x04) - SecurityCmd_MessageEncap (AssociationCmd_Set) (Node=68): 0x01, 0x1f, 0x00, 0x13, 0x44, 0x18, 0x98, 0x81, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x25, 0x19, 0xc7, 0xda, 0x1e, 0x7a, 0xda, 0x5b, 0x41, 0x2a, 0x0f, 0xea, 0x87, 0xdd, 0x25, 0xb0, 0x33
2015-04-23 20:11:35.247 Detail, Node068,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
2015-04-23 20:11:35.247 Detail, Node068,   ZW_SEND_DATA delivered to Z-Wave stack
2015-04-23 20:11:35.267 Detail, Node068,   Received: 0x01, 0x05, 0x00, 0x13, 0xb0, 0x00, 0x59
2015-04-23 20:11:35.268 Detail, Node068,   ZW_SEND_DATA Request with callback ID 0xb0 received (expected 0xb0)
2015-04-23 20:11:35.268 Info, Node068, Request RTT 29 Average Request RTT 28
2015-04-23 20:11:41.240 Detail, 
2015-04-23 20:11:41.241 Info, Node068, Sending (Security) message (Attempt 3, Callback ID=0xb1, Expected Reply=0x04) - SecurityCmd_MessageEncap (AssociationCmd_Set) (Node=68): 0x01, 0x1f, 0x00, 0x13, 0x44, 0x18, 0x98, 0x81, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x25, 0x19, 0xc7, 0xda, 0x1e, 0x7a, 0xda, 0x5b, 0x41, 0x2a, 0x0f, 0xea, 0x87, 0xdd, 0x25, 0xb1, 0x32
2015-04-23 20:11:41.270 Detail, Node068,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
2015-04-23 20:11:41.270 Detail, Node068,   ZW_SEND_DATA delivered to Z-Wave stack
2015-04-23 20:11:41.272 Detail, Node068,   Received: 0x01, 0x05, 0x00, 0x13, 0xb1, 0x00, 0x58
2015-04-23 20:11:41.273 Detail, Node068,   ZW_SEND_DATA Request with callback ID 0xb1 received (expected 0xb1)
2015-04-23 20:11:41.273 Info, Node068, Request RTT 31 Average Request RTT 29
2015-04-23 20:11:47.242 Error, Node068, ERROR: Dropping command, expected response not received after 3 attempt(s)
2015-04-23 20:11:47.243 Detail, Node068, Removing current message

**Pull request closed without merging**
