### PR TITLE
Update for Zooz ZEN21v3, add Zooz ZEN24v2 config

### PR DESCRIPTION
**Pull request by cybergrimes**
Config XML for v3 hardware incorrectly labeled v2, manufacturer specific entry was never pointed to config XML after created. Everything was pointing to the original v1/v2 XML.

### CODE REVIEW

**Comment by cybergrimes** [comment]
reopened #2251

**Comment by cybergrimes** [comment]
reopened as #2251

**Comment by cybergrimes** [comment]
Notes on the ZEN24v2 config:
1- I'm unsure how to handle "ZWProductPage", the ZWAlliance page is for V1 hardware which is not capable of these advanced settings. It has the old manufacturer ID also. There's no other ZEN24 page on the site that I can find to use here so I omitted it from the entry.

2- The manual on the ZWAlliance page is also for the older hardware so I linked the one from TheSmartestHouse page. It seemed inappropriate to use an outdated manual.

**Comment by Fishwaldo** [comment]
Looks Good! Thanks

**Comment by cybergrimes** [comment]
Sorry about these typos, I'll check closer in future

**Comment by Fishwaldo** [comment]
Next time you can run "make xmltest" to check before opening the PR's

**Comment by cybergrimes** [comment]
> 
> 
> Next time you can run "make xmltest" to check before opening the PR's

will do, thanks

**Pull request merged**
