### PR TITLE
Add support for Zooz ZSE29

### LINKED ISSUE #1809: Add support for Zooz ZSE29, Outdoor Motion Sensor
The Zooz ZSE29 is an Outdoor Motion Sensor. It has no configuration parameters (configuration is done manually on the physical device)

### PR DESCRIPTION
**Pull request by zlalanne**
Adds support for the ZSE29 Outdoor Motion Sensor from Zooz. The device does not
use Z-Wave for configuration. There are manual knobs on the device to configure
the device.

Z-Wave Product Catalog page for reference:
https://products.z-wavealliance.org/products/3081

Tested this with an actual device using OpenZWave through Home Assistant.

Resolves #1809.

### CODE REVIEW

**Comment by TomBrandt** [comment]
Just curious. Zooz ZSE29 is advertised to work with Home assistant and doesn't. I wonder how long before this update shows up. Or any update for that matter. I wonder how long does an update take to get through vetting and added to the database?

**Comment by Fishwaldo** [comment]
Home assistant uses a forked version that is 1 major version behind OZW. So you should ask the HA devs this question. 

There doesn’t appear to be any real urgency from HA to upgrade currently despite my offers to assist with questions etc.

**Comment by TomBrandt** [comment]
Justin 

Thank you. And it figures. Not being anybody in this arena I was just curious to it all. And you have answered my question. And I thank you for that. 

Tom B. 

Tom's iPhone

**Comment by zlalanne** [comment]
@TomBrandt there is a configuration option in Home Assistant to use a custom OpenZWave config directory. I use this to run with the latest commit of OpenZWave

https://www.home-assistant.io/docs/z-wave/installation/#config_path

**Comment by TomBrandt** [comment]
Zack

Thanks. I have since reading a review of the Zooz ZSE29. It’s now in but not reporting motion. Probably due to me. So I’ll keep trying. Beating my head against wall syndrome. 

Tom's iPhone

**Comment by Fishwaldo** [comment]
Using config files from 1.6 of OZW will not work as expected with HA. The format has evolved and is not fully backwards compatible

**Pull request merged**
