### PR TITLE
Add LB60Z-1 Dimmable LED Light Bulb

### PR DESCRIPTION
**Pull request by KyleARector**
Adding support for the Linear (GoControl) dimming light bulb. 

Product information can be found at: http://products.z-wavealliance.org/products/1291

### CODE REVIEW

**Comment by nechry** [comment]
@KyleARector but please don't touch the ChangeLog. 
also you device include configuration parameter, so complet your PR with a specific device file
http://products.z-wavealliance.org/products/1291/configs
check also the association groups, only one for this named "Lifeline"

**Comment by KyleARector** [comment]
Apologies for the ChangeLog, I misunderstood the README. I have added the specific config and made the necessary changes to the entry in manufacturer_specific.xml

**Comment by nechry** [comment]
you did not add the COMMAND_CLASS_ASSOCIATION section

**Comment by nechry** [comment]
for ChangeLog we will update it and also we have to update the distfiles.mk file in case of new file.

**Comment by KyleARector** [comment]
Understood, I appreciate it.

**Pull request merged**
