### PR TITLE
Implemented simple ReopenLogFile

### PR DESCRIPTION
**Pull request by electrofloat**
This is a base for https://github.com/OpenZWave/open-zwave/issues/465

### CODE REVIEW

**Comment by Fishwaldo** [comment]
This doesn't really do anything (especially if AppendLog is true) as it just closes and opens the log file. For rotation, we need to rename the old log file and start a new one (regardless of AppendLog) so yes - a base, but still needs some work.

**Comment by electrofloat** [comment]
> This doesn't really do anything (especially if AppendLog is true) as it just closes and opens the log file.
Exactly.

> For rotation, we need to rename the old log file and start a new one (regardless of AppendLog) so yes - a base, but still needs some work.

The rotation is the not job of the lib itself. Logrotate does the rotation (on linux), sends a SIGHUP to the app, the app calls ReopenLogfile in the lib, which reopens the same logfile and everything works as expected.

**Comment by Fishwaldo** [comment]
Your assuming Linux and Systems with logrotate. Windows/Mac/Solaris etc etc etc may not/do not have such a thing. Hence the actual rename of the log file should be done in the library.

I appriciate the PR - I'll update it eventually. :)

**Comment by electrofloat** [comment]
That is true. Since the issue was mainly talking about logrotate (https://github.com/OpenZWave/open-zwave/issues/465#issuecomment-211425247) and not handling SIGHUP in the lib (https://github.com/OpenZWave/open-zwave/issues/465#issuecomment-211913649)

That is what I implemented. I'd really appreciate some kind of logrotation for the log it creates either by logrotate or by any other means.

**Comment by Fishwaldo** [comment]
It just needs a rename between the close/open calls... (but needs to implemented in the platform abstraction classes so its portable). 

Question begs - What do we rename to, and how do we handle duplicates etc. 

I'll get to it one day :)

**Comment by Fishwaldo** [comment]
Related to #2146

**Comment by Fishwaldo** [comment]
Merged to Dev Branch. Thanks!

**Pull request closed without merging**
