### PR TITLE
Added Fibaro FGWDS221 Walli Double Switch

### PR DESCRIPTION
**Pull request by TerrorSource**
Added "FGWDS221 Walli Double Switch" to manufacturer_specifiec.xml
Added /config/fibaro/fgwds221.xml file with all z-wave config's from https://products.z-wavealliance.org/products/3395/configs

### CODE REVIEW

**Comment by Fishwaldo** [comment]
please run make xmltest and fix up the problems it reports.

**Comment by TerrorSource** [comment]
@Fishwaldo Cant run "make xmltest"
pi@raspberrypi:~/open-zwave $ make xmltest
Makefile:50: *** xmllint command not found..  Stop.

**Comment by petergebruers** [comment]
Almost there... I'll fix up the last bits for you. The "revisions" can be a moving target...

**Comment by TerrorSource** [comment]
@petergebruers thanks! Didn't knew i had to edit that also.
Now working on the Fibaro Walli Dimmer config. PR will be made in a few days.

**Comment by petergebruers** [comment]
Thanks!

**Pull request merged**
