### PR TITLE
Fix for CPU-spinning on device disconnection

### PR DESCRIPTION
**Pull request by stromnet**
Hi,
this is an attempt to fix the issue with disconnected devices, which currently isn't handled very well.

If a serial port device was disconnected, we got stuck in read loop burning CPU cycles and having a unusable device.

On disconnect (at least on FreeBSD), select() will return 1 indicating
FD ready to read. The subsequent read() would however return 0. This would would go on until the process was killed, yielding unusable device, and high CPU usage.
With this patch, we break out of the read loop and re-init the connection if this condition occurs.

This has been tested on FreeBSD 10.1 with an Aeon Labs 2 dongle. On this setup, disconnecting and then reconnecting the device works without any problems, and communication seems to be restored. I'm not sure if there are any higher-level issues with this though, there may be buffers which should be flushed on re-init or similar?

Testing should be done on other supported platforms to verify that it works.

### CODE REVIEW

**Comment by Fishwaldo** [comment]
Hi,
This issue has already been discussed in Issue 111. You patch only addresses a small part of it. We still need to propagate the disconnect up the stack (to the Driver and then to the Manager, and of course consider a notification to the Application).

Just re-opening the Serial Port is not the complete fix here. We would probably need to also re-init the Controller. 

Also, I think most times, the issue here is going to be more along the lines of the USB stick going unresponsive or falling out. At the moment, if the stick is not re-inserted, we will just spin, and instead of consuming CPU, we will start consuming memory and the message queues build up. :)

I will ultimately merge this, but I think it needs more work to address the issue. Thanks for getting started on this.

**Comment by stromnet** [comment]
Ok, kind of what I expected, but this is a start at least!

An alternative to the current behaviour would just be to log "Crap, we're dead" and just stop reading (but not reconnect). Then at least we have notified the user that there is a problem, and we won't waste CPU/power for no good reason.

**Comment by Fishwaldo** [comment]
My plan is to issue a Driver Failed notification and unload the Driver. There are a few race conditions though that make it tricky. (One being the driver thread handles the dispatch of notifications etc.) 

We will probably have to put a condition variable in the Serial API (as it's threaded) and in the main loop of the driver check it and then call the notification, and subsequently signal the exit event.

**Comment by stromnet** [comment]
Sounds like a good idea, this way the application can re-init the library (if possible, not too familiar with the details. Otherwise just restart).

**Comment by Fishwaldo** [comment]
Hi,
Apologies, I just cleaned up the repo, removing old object files from way back when. This has resulted in PR's being messed up. Could you please redo the PR after pulling a new fork (the repo should be much smaller now though)

Thanks

**Comment by stromnet** [comment]
Leaving this as-is as this seems discussed in #111 which is still open.

**Pull request closed without merging**
