### PR TITLE
Added Zooz ZEN20/23/24 configs

### PR DESCRIPTION
**Pull request by mcd1992**
ZEN23 - http://a.co/38I7fJ1
ZEN24 - http://a.co/2VGVCDs

### CODE REVIEW

**Comment by nechry** [comment]
please add specific devices configuration files
ZEN23 
http://products.z-wavealliance.org/products/2058
ZEN24 
http://products.z-wavealliance.org/products/2060
With parameter and association group

**Comment by mcd1992** [comment]
Alright, this should be correct. Let me know if I missed anything or did something wrong.

Thanks

**Comment by nechry** [comment]
I think it's more easier to read if you use a list instead of a boolean. But if you think not, I will merge, nothing is wrong.

**Comment by mcd1992** [comment]
I'll swap it to a list.

**Comment by mcd1992** [comment]
@nechry should be good now.

Thanks.

**Pull request merged**
