### PR TITLE
Update fgcd001.xml

### PR DESCRIPTION
**Pull request by rkuijer**
Refactor to reflect the provided configuration
Source: 
* FGCD-001-EN-T-v0.4.PDF
* http://products.z-wavealliance.org/products/2336/configs

### CODE REVIEW

**Comment by tlpeter** [comment]
Thanks for adjusting the file. Was my first time i created one.
But are you sure that index 3 and 4 are correct? Right now there isn't an option for 7 (all enabled)

**Comment by nechry** [comment]
I just see and fix back

**Comment by tlpeter** [comment]
Are you sure? now option 4 is missing. (zwave range)
There should be an option for selecting some options like 1 and 4 (=5) or 2 and 4 (=6)
So the max 7 should be used i think and all different options should be selectable i think.
This is my first attempt so maybe i am wrong and please tell if i am.

**Comment by rkuijer** [comment]
I know what you mean. And it's also the first time for me.
But when I look at the specification this is what it should be like.
Also the manual of [Fibaro ](http://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/2336/FGCD-001-EN-T-v0.4.pdf) states these items. I can see if I can let somebody verify it on a Fibaro Home Center.  
So it could be that you are right and Fibaro made a mistake

**Comment by tlpeter** [comment]
Funny thing, i just checked for these options on the smoke detector (fgsd-002) and has these options:

`<Value type="list" genre="config" instance="1" index="2" label="Z-Wave notifications status" min="0" max="3" value="0"  size="1">
			<Help>This parameter allows to activate excess temperature and/or enclosure opening notifications sent to the main controller.</Help>
			<Item label="all notifications disabled" value="0" />
			<Item label="enclosure opening notification enabled" value="1" />
			<Item label="exceeding temperature threshold notification enabled" value="2" />
			<Item label="all notifications enabled" value="3" />
		</Value>

		<Value type="list" genre="config" instance="1" index="3" label="Visual indicator notifications status" min="0" max="7" value="0"  size="1">
			<Help>This parameter allows to activate visual indications but does not apply to major alarms, such as FIRE, TROUBLE and LOW BATTERY ALARM.</Help>
			<Item label="all notifications disabled" value="0" />
			<Item label="enclosure opening notification enabled" value="1" />
			<Item label="exceeding temperature threshold notification enabled" value="2" />
			<Item label="enclosure opening and exceeding temperature threshold notifications enabled" value="3" />
			<Item label="lack of Z-Wave range notification" value="4" />
			<Item label="enclosure opening and lack of Z-Wave range notifications enabled" value="5" />
			<Item label="exceeding temperature threshold and lack of Z-Wave range notifications enabled" value="6" />
			<Item label="all notifications enabled" value="7" />
		</Value>

		<Value type="list" genre="config" instance="1" index="4" label="Sound notifications status" min="0" max="7" value="0"  size="1">
			<Help>This parameter allows to activate sound signals but does not apply to major alarms, such as FIRE, TROUBLE and LOW BATTERY ALARM.</Help>
			<Item label="all notifications disabled" value="0" />
			<Item label="enclosure opening notification enabled" value="1" />
			<Item label="exceeding temperature threshold notification enabled" value="2" />
			<Item label="enclosure opening and exceeding temperature threshold notifications enabled" value="3" />
			<Item label="lack of Z-Wave range notification" value="4" />
			<Item label="enclosure opening and lack of Z-Wave range notifications enabled" value="5" />
			<Item label="exceeding temperature threshold and lack of Z-Wave range notifications enabled" value="6" />
			<Item label="all notifications enabled" value="7" />
		</Value>`

**Comment by tlpeter** [comment]
Is there a way that i can change it or is that option gone now when it is closed?
This is from the Fibaro site:

`
This parameter allows to set the actions which result in sending notifications to the Z-Wave network controller.
Available settings:
0 – both actions disabled
1 – tampering (opened casing)
2 – exceeding the temperature
3 – both actions enabled
Default setting: 0
Parameter size: 1 [byte]
`

`
This parameter allows to set the actions which result in LED diode indications. This parameter does not apply to the most important actions, such as CO Alarm, Malfunction Alarm and Low Battery Alarm.
Available settings:
0 – all notifications disabled
1 – tampering (opened casing)
2 – exceeding the temperature
4 – lack of Z-Wave range
Default setting: 0
Parameter size: 1 [byte]
Parameter 3 values may be combined, e.g. 1+2+4=7 means that all actions will be active.
`

`
This parameter allows to set the actions which result in acoustic signals. This parameter does not apply to the most important actions,
such as CO Alarm, Malfunction Alarm and Low Battery Alarm.
Available settings: 0-7
0 – all notifications disabled
1 – tampering (opened casing)
2 – exceeding the temperature
4 – lack of Z-Wave range
Default setting: 0
Parameter size: 1 [byte]
Parameter 4 values may be combined, e.g. 1+2+4=7 means that all actions will be active.`

**Comment by rkuijer** [comment]
Great input, not in the manual

**Comment by rkuijer** [comment]
Is see that it's already corrected:
https://github.com/OpenZWave/open-zwave/commit/c6553abcb325cfd5235a752cdbcd8c4cd9e70116

**Comment by tlpeter** [comment]
Not completely as index 3 and 4 are missing options.
See my last comment.

**Comment by rkuijer** [comment]
The usage at the moment it's like a bit field you can combine.
That's why on decimal 3 there is no option defined, because you are combining option 1+ 2, bit wise
Every bit within the byte stands for a option.

The smoke detector has got also only 3 options:
- enclosure opening
- exceeding temperature threshold
- lack of Z-Wave range
The CO detector has got the same options

Please explain what you are missing?

**Comment by tlpeter** [comment]
What i am missing is the combinations.
So i want notifications for 1 and 4 which is 5 and this is a valid option (1 till 7)
Now i can choose between 1,2,4 or 7 which is all.
The options should be 1 only, 2 only, 4 only or a combination of any of these
1
2
1+2=3
4
1+4=5
2+4=6
1+2+4=7

Then these are the values:

`<Item label="all notifications disabled" value="0" />
			<Item label="enclosure opening notification enabled" value="1" />
			<Item label="exceeding temperature threshold notification enabled" value="2" />
		 	<Item label="enclosure opening and exceeding temperature threshold notifications enabled" value="3" />
			<Item label="lack of Z-Wave range notification" value="4" />
			<Item label="enclosure opening and lack of Z-Wave range notifications enabled" value="5" />
			<Item label="exceeding temperature threshold and lack of Z-Wave range notifications enabled" value="6" />
			<Item label="all notifications enabled" value="7" />`

**Comment by rkuijer** [comment]
I don't think the combined values have to be provided as separated values. 
The configuration value is not a list so you can provide these values.
The configuration parameter has got a min-max, everything between these can be provide as valid values. 
If it would be defined as a list you indeed need to provide the values in between, but not at the moment(byte).

Please correct me if i'm wrong.

**Comment by tlpeter** [comment]
Can you check the xml for the fgsd002?
Check parameter 3 and 4 and you will see what i mean.
I use Domoticz and if i go to such a smoke detector then i have a dropdown with all the options like disable all, enable all or any combination of those.

**Comment by rkuijer** [comment]
I also use Domoticz and no you don't have a drop down if it's defined as a byte.
You can just provide a value like parameter 7 for instance.

**Comment by tlpeter** [comment]
That is odd as i do have a list even when it is set as byte.

**Comment by nechry** [comment]
a list item for param 3 and 4 is a option but I think the bitset still the good way to set this parameter. I just fix again the max value to7 for 3 and 4. in the linked pdf the note explain is a combined value
http://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/2336/FGCD-001-EN-T-v0.4.pdf

**Pull request merged**
