### PR TITLE
Add Support for All Zen22V2 Features

### PR DESCRIPTION
**Pull request by cliffbraun**
I mostly just needed the ability to set the 3-way option to momentary switches, but went through this document and added all features:https://www.support.getzooz.com/kb/article/319-zooz-dimmer-zen22-ver-3-05-advanced-settings/

### CODE REVIEW

**Comment by cliffbraun** [comment]
Whoops, there is actually a physical v3 rev, Need to separate out from V2

**Comment by Fishwaldo** [comment]
It would be great if you could add the MetaData Block as per https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices#creating-the-metadata-block

**Comment by bepsoccer** [comment]
I have submitted a pull request for a newer version of firmware for the Zen22v2 that includes the MetaData Block

**Comment by cliffbraun** [comment]
> I have submitted a pull request for a newer version of firmware for the Zen22v2 that includes the MetaData Block
> 
> #2185

Awesome, good to see them supporting the community and thanks for doing the work! Closing this one.

**Pull request closed without merging**
