### PR TITLE
Fixed a problem with lifeline group 1.1

### PR DESCRIPTION
**Pull request by Olifant1990**
- Added <ForceInstances>false</ForceInstances> to associations class
- Reformatted XML file.

### CODE REVIEW

**Comment by Olifant1990** [comment]
See https://www.domoticz.com/forum/viewtopic.php?f=24&t=29715#p225812 for problem and solution details

**Comment by petergebruers** [comment]
I understand what you are doing and what this is about, however... I would like to put this on hold because there was a change in OpenZWave that may affect this type of device...

Issues with a similar device were reported, and as mentioned in this comment, a change was made to  OpenZWave...

https://github.com/OpenZWave/open-zwave/issues/1895#issuecomment-558065546

That is Commit 027d7436 by Justin Hammond, 11/25/2019 10:24 AM, "Check if MultiChannel is present on a device before trying to add a MCA with a instance, otherwise fall back to plan associations - Issue #1895"

I would like to know if you've tested this with a OZW version before or after this date. You can post the version listed at the start of OpenZWave but it is not 100% reliable. The most reliable way is for you to build Domoticz & OpenZWave from source...

**Comment by Olifant1990** [comment]
Domoticz (v. 4.11595) says it is version 1.6.989.g9526554b.dirty.
That build is of 29/12/2019, but the OpenZwave version in the source of Domoticz isn't updated yet..
I do not have the possibility to run my live environment on a test environment, so I'll have to wait till this rolls over to the Domoticz source/ beta builds.

**Comment by gizmocuz** [comment]
@Olifant1990 , you can always build domoticz/openzwave yourself, but i merged the latest OZW code Sunday

**Comment by Fishwaldo** [comment]
Ping?

**Comment by Olifant1990** [comment]
Oh sorry!
I have updated Domoticz past Sunday, will try to test if the lifeline group is working now somewhere this week. I guess I need to remove the device out of the zwave cache file, so it will be newly interviewed?
And them remove/add the lifeline group?

**Comment by Olifant1990** [comment]
I have removed the z-wave cache and let it rebuild.
This is the result of the association class:
`<CommandClass id="142" name="COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION">
				<Compatibility />
				<State>
					<Encrypted>true</Encrypted>
					<StaticRequests>4</StaticRequests>
				</State>
				<Instance index="1" />
				<Associations num_groups="9">
					<Group index="1" max_associations="1" label="Lifeline" auto="true" multiInstance="true">
						<Node id="1" instance="1" />
					</Group>
					<Group index="2" max_associations="16" label="basic on/off (triggered at change of the input I1 state and reflecting its state)" auto="false" multiInstance="true" />
					<Group index="3" max_associations="16" label="basic on/off (triggered at change of the input I2 state and reflecting its state)" auto="false" multiInstance="true" />
					<Group index="4" max_associations="16" label="basic on/off (triggered at sensing moving direction of roller: up=FF, down=0)" auto="false" multiInstance="true" />
					<Group index="5" max_associations="16" label="basic on/off (triggered at reaching roller position: bottom=FF, top=0)" auto="false" multiInstance="true" />
					<Group index="6" max_associations="16" label="basic on/off (triggered at reaching roller position: bottom=FF, not bottom=0)" auto="false" multiInstance="true" />
					<Group index="7" max_associations="16" label="multilevel set (triggered at changes of value of the Flush shutter DC position)" auto="false" multiInstance="true" />
					<Group index="8" max_associations="16" label="multilevel set (triggered at changes of value of slats tilting position)" auto="false" multiInstance="true" />
					<Group index="9" max_associations="16" label="multilevel sensor report (triggered at change of temperature sensor)" auto="false" multiInstance="true" />
				</Associations>
			</CommandClass>`

Still multiInstance="true". But I guess not supported by the device.
Tried to remove group "1.1" and readd group "1", but will be saved as group 1.1 again.

**Comment by petergebruers** [comment]
@Olifant1990 thank you for reporting back. It might be a peculiarity of this device and I'll accept your PR in that case, but there is one bit of information missing... What version of OZW? In OZW_Log.txt?

**Comment by Fishwaldo** [comment]
You may have to actually exclude/include or use OZWCP to remove the association from lifeline to see if this is fixed. Simply deleting the ozwcache is not enuf.

**Comment by petergebruers** [comment]
> You may have to actually exclude/include or use OZWCP to remove the association from lifeline to see if this is fixed. Simply deleting the ozwcache is not enuf.

Good catch... Being a Qubino, some parameters might "stick" even when you exclude (by design) so maybe even need "factory reset" to really start with a clean situation... imho...

@Fishwaldo you agree, it would really be nice to have as few options in the config files as possible, and rely on OZW interview process to configure devices, right? So it would be really nice if @Olifant1990 could test this properly.

**Comment by Olifant1990** [comment]
Todat I had some time to test.
- I excluded the qubino flush shutter from my network.
- performed a factory reset
- reincluded the device
- saw there was no association in the lifeline group, clicked on the plus in Domotics and typed in "1".
- And back is the 1.1 group :(

Domoticz v4.11724, from past sunday (23-02-2020)
Saying it has OpenZwave version 1.6.1019.g0d94c942.dirty

**Comment by petergebruers** [comment]
Thank you for reporting back, based on that info I conclude you really need that ForceInstances False in the config file. I'll have a look at the PR today.

**Comment by petergebruers** [comment]
Hmm... qubino/ZMNHCDx.xml:147: element Compatibility: Schemas validity error : Element '{https://github.com/OpenZWave/open-zwave}Compatibility': This element is not expected. Expected is ( {https://github.com/OpenZWave/open-zwave}Group ).
/Users/peter/ozw/open-zwave/config/qubino/ZMNHCDx.xml fails to validate

Please move that element to the line above and retest your config file, because this PR cannot have solved your issue,  it is invalid... Maybe a copy/paste error?

After that, if you are on Linux or Mac, run "make xmltest" to validate and push your changes to this PR. If you cannot run make xmltest I'll do that for you.

**Comment by nechry** [comment]
thank @Olifant1990

**Pull request merged**
