### PR TITLE
Add Qubino ZMNHCDx support

### PR DESCRIPTION
**Pull request by guillaumezin**

### CODE REVIEW

**Comment by guillaumezin** [comment]
Ok, found out some doc here https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by Fishwaldo** [comment]
Merged. If there is a issue we can always update later.

**Comment by xabix** [comment]
Thank you guys! Looking to get this applied to my config (through Jeedom using 1.3.523)

I assume I can just pull the file manually in between?

**Comment by nechry** [comment]
@xabix we can't merge this version in jeedom. we must perform a dependencies update with latest ozw lib and for this publish a new version of zwave plugin. the new plugin zwave will come with jeedom V2.0. This change give us some pain to merge all existing devices config not yet merged to ozw. or for compatibility issues we must keep the auto=true for group 1 went is need.  We have many devices config in jeedom with little fix to merge and some not yet exist in ozw. 

for all qubino I decide to use a region free approach with a x at end like:
Qubino: ZMNHCDx Flush shutter zwave+
ZMNHCD1 868,4 MHz
ZMNHCD2 921,4 MHz
ZMNHCD3 908,4 MHz
ZMNHCD4 869,0 MHz
ZMNHCD5 916,0 MHz 
<Product type="0003" id="0052" name="ZMNHCDx Flush Shutter" config="qubino/ZMNHCDx.xml"/>

**Comment by Fishwaldo** [comment]
Nechry... thats the problem with "forking" ozw I guess... :)

when am I getting the next PR for configs?

**Comment by nechry** [comment]
Yes, but we can validate with user before submit to ozw. The config file is "normally" tested by many users. 

I got lot of pain with Qubino device, not specially this one but double relay is real pain.

The merge must be postpone, we can update to the ozw latest version now and because you remove the auto=true in old config file we will loose all controller association on new included device. so the config with old lib 1.3.597 is not good.

I will see what we can do, I know you wait and hope for many of config file from us I you see the git activity we have many in delta with ozw now. we plan to make a PR every 2 weeks it's 2 months now...

Last thing, some users have also report Qubino will wrote for us the config file, see her a email copy:
```
Thank you very much for buying Qubino products.

Yes, we plan to do it in Q1 2016.

Please, let me know if you need more help.

Best regards/Lep pozdrav,

Marko Danevcic
```

Do you have also this informations from your side?

**Comment by Fishwaldo** [comment]
I've already reached out to Qubino to offer support. No Reply unfortuantly.

They have buggy devices as far as I can tell, but I can't help them if they don't want to help themselves.....

**Comment by nechry** [comment]
I will try to, and also try from domadoo shop they have contact

**Pull request merged**
