### PR TITLE
PoPP 10-Year Smoke Detectors Fix

### PR DESCRIPTION
**Pull request by rubimart**
I added the Popp 700342 10-Year Smoke Detector (without siren) to the manufacturer_specific.xml and the new 700342.xml file. I fixed names in the manufacturer_specific.xml. The picture file is the same.

### CODE REVIEW

**Comment by rubimart** [comment]
This is my first contribution. Sorry for the mistakes if I have!

**Comment by petergebruers** [comment]
Hi! Thank you for contributing.

Unfortunately you'll have to check and fix something...

```xml
<Product config="popp/009402.xml" id="0004" name="009402 10-Year Smoke Detector with Siren" type="0004"/>
<Product config="popp/700342.xml" id="0004" name="700342 10-Year Smoke Detector" type="0004"/>
```

Both lines say id 4 and type 4 - that cannot be correct. 

Please check the manufacturer documentation to match the IDs and check with the device you own...

I've done a quick check myself and I see:

https://manuals.zwave.eu/backend/make.php?lang=en&sku=pope700342&type=popp

It says: 0x0154.0x0004.0x000D so I would say the 700342 has id 000d and type 0004

The other one...

https://manuals.zwave.eu/backend/make.php?lang=en&sku=pope009402&type=popp

Z-Wave Product Id 0x0154.0x0004.0x0004

**Comment by rubimart** [comment]
Hi!
Thank You! Sorry for the inaccuracy.

**Comment by petergebruers** [comment]
Thanks! Your commits have been squashed, you'll have to check if you still have local unsaved work on your master branch and if you have none then do "git fetch origin" and "git reset --hard origin/master # Destroys your local work"

**Pull request merged**
