### PR TITLE
fixing relative include paths

### PR DESCRIPTION
**Pull request by Oinosseus**
Internal test script do not see this issue since src/ is directly
included. But when open-zwave is installed header are located in
/usr/local/include/openzwave/ while only /usr/local/include/ is
included.

### CODE REVIEW

**Comment by Fishwaldo** [comment]
I think you have something funky going on here. I have no problems with installed versions (via packages or source) and compiling 3rd party applications. 

Can you give some concrete examples (with compiler include paths shown) where this is failing.

**Comment by Oinosseus** [comment]
Hello Justin,

I created a little example: [https://github.com/Oinosseus/ozw_test.git](https://github.com/Oinosseus/ozw_test.git)

When I build it I got this:

```
thomas@OinoDesk:~/Dokumente/ozw_test_build> cmake ../ozw_test && make
CMake Warning (dev) in CMakeLists.txt:
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/thomas/Dokumente/ozw_test_build
Scanning dependencies of target ozw_test
[ 50%] Building CXX object CMakeFiles/ozw_test.dir/main.cpp.o
In Datei, eingebunden von /home/thomas/Dokumente/ozw_test/main.cpp:1:
/usr/local/include/openzwave/value_classes/ValueID.h:34:10: schwerwiegender Fehler: ValueIDIndexes.h: Datei oder Verzeichnis nicht gefunden
   34 | #include "ValueIDIndexes.h"
      |          ^~~~~~~~~~~~~~~~~~
Kompilierung beendet.
make[2]: *** [CMakeFiles/ozw_test.dir/build.make:63: CMakeFiles/ozw_test.dir/main.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/ozw_test.dir/all] Fehler 2
make: *** [Makefile:84: all] Fehler 2
```

From ValueID.h it is not possible to find ValueIDIndexes.h. This is because the include is done with quotes which sets the current file directory as relative search path. But ValueID.h is in value_calasses/ and ValueIDIndexes.h is one directory up.

I am using cmake, gcc, on an openSuse system. The ozw headers are installed in /usr/local/include/openzwave/. The system include path is /usr/local/include/.
If I directly set the include path to /usr/local/include/openzwave/ it works again because ValueIDIndexes.h is again in a search path, but this is not the intended way in a system. You can test it by uncommenting line 5 in CMakeList.txt

My reworked include paths solve this issue. Another solution could be to use system includes instead of relative includes (eg #include <openzwave/ValueIDIndexes.h>)

Regards,
Thomas

P.S. Sorry for the german language compiler output.
P.P.S. Thank you for working on OZW!

**Comment by petergebruers** [comment]
@Oinosseus I understand what you are doing... Does your PR fix all issues? IMHO you are not fixing *all* relative pathis in OZW

**Comment by petergebruers** [comment]
BTW I was testing with cmake myself the other day and I used an idea from another user to find and link, I did not dig too deeply into that, but here it is...

```txt
# openzwave library - idea copied from:
# https://github.com/belyalov/open-zwave-mqtt/blob/master/CMakeLists.txt

find_library(OPENZWAVE_LIB PATH_SUFFIXES lib lib64 NAMES libopenzwave.so libopenzwave.dylib)
if(NOT OPENZWAVE_LIB)
  message(FATAL_ERROR "open_zwave library not found.")
endif()

# openzwave headers
find_path(OPENZWAVE_INCLUDES openzwave/Manager.h)
if(NOT OPENZWAVE_INCLUDES)
  message(FATAL_ERROR "open_zwave library headers not found")
endif()

message(STATUS "OpenZwave Includes:  ${OPENZWAVE_INCLUDES}")
message(STATUS "OpenZwave Libraries: ${OPENZWAVE_LIB}")

include_directories(${OPENZWAVE_INCLUDES} ${OPENZWAVE_INCLUDES}/openzwave)

set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

# add the executable
add_executable(print_secure_node print_secure_node.cpp)

target_link_libraries(print_secure_node ${OPENZWAVE_LIB})
```

**Comment by Oinosseus** [comment]
In my project I have a running system using the manager, notification and valueid classes.
But I guess I am not using all the functionality ozw offers. So you are right, its very likely that I didn't found all includes.
I can do a review again. Do you know a way how to test it?

The CMake example puts the openzwave/ directory into the includes. This works but it is not the intended way how how things should work.

**Comment by petergebruers** [comment]
> I can do a review again. Do you know a way how to test it?

I guess you could run "gcc" manually on each individual file. It will bark if it doesn't find the files.

> The CMake example puts the openzwave/ directory into the includes. This works but it is not the intended way how how things should work.

No, I guess the author of that workaround also struggled with paths, if you can make it work with this line and your PR instead of my "workaround" that is clearly better

`target_link_libraries(ozw_test pthread openzwave)`

BTW, "for fun and giggles" I tried to compile the OZW library, without your patch, and by not using the "Makefile" of OZW.

It turns out that is possible and requires no editing... There is some "magic" going on in compilers to determine the true paths of include files and "it just works".

I tried with an old and new gcc by using docker.

```docker
FROM ubuntu:16.04
RUN apt-get update -y &&  apt-get install -y gcc git build-essential vim-common curl wget
RUN git clone https://github.com/OpenZWave/open-zwave.git
```

I then start a container

docker run -it build-c

root@675e0618f56e:/# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

```
cd open-zwave/cpp/src
rm -r *o

cat << EOF > vers.cpp
#include "Defs.h"
uint16_t ozw_vers_major = 1;
uint16_t ozw_vers_minor = 6;
uint16_t ozw_vers_revision = 9999;
char ozw_version_string[] = "1.6-999-fakeversion";
EOF

gcc -std=c++11 -c -I. -I../tinyxml *cpp
gcc -std=c++11 -c -I. -I../tinyxml command_classes/*cpp
gcc -std=c++11 -c -I. platform/*cpp
gcc -std=c++11 -c -I. platform/unix/*cpp
gcc -std=c++11 -c -I. -I../tinyxml value_classes/*cpp
gcc -c -I. aes/*c
gcc -std=c++11 -c ../tinyxml/*cpp
gcc -std=c++11 -c -I. ../examples/MinOZW/Main.cpp
gcc *o -l resolv -l stdc++ -pthread -o MinOZW 2>&1 | more

-> MinOZW is functional...
```

Now the "-I" parts are essential.

If you do `gcc -std=c++11 -c *cpp 2>&1 | more` you will get the errors that you are trying to fix:

```
In file included from CompatOptionManager.cpp:28:0:
command_classes/CommandClass.h:34:18: fatal error: Defs.h: No such
file or directory
compilation terminated.
In file included from Driver.h:37:0,
                 from DNSThread.h:36,
                 from DNSThread.cpp:28:
value_classes/ValueID.h:34:28: fatal error: ValueIDIndexes.h: No su
ch file or directory
```

If you try to compile everything without "-I" I thik you'll find more relative paths.

Can you give that a try and push extra commits? I have to go now, I'll be back on Sunday.

**Comment by petergebruers** [comment]
@Fishwaldo you're the maintainer but I think it would be nice if OpenZWave could work with cmake "out of the box". I do not have much experience with this so I value your opinion...

**Comment by Oinosseus** [comment]
With your idea I found this command to test it:
```
cd cpp/src/
find . -name "*.cpp" | xargs -L1 g++ -c -lpthread -lopenzwave -otest
```
It compiles each source file separately and brought up a lot of path issue.
I'm reworking and give a notice when done ...

**Comment by Fishwaldo** [comment]
I doubt I’ll accept this unless things are broken. Using pkg-Config with OZW should solve the include path problems.

**Comment by Oinosseus** [comment]
Hm, too sad. I spend the effort and finished now reworking all other includes.

I did use the following for identifying all include paths:
```
cd cpp/
find src -name "*.cpp" | xargs -L1 g++ -c -lpthread -lopenzwave -ofoo -Itinyxml
```
(This brings now only errors because of missing windows.h)

I checked that all tests are pass (make test) and I checked by using it with my project. For me it seems okay, but I could only test on linux (no windows/windowsRT).

I think my rework corrects the relative include paths. Includes with quotes are relative from the file location not relative to an "-I" include.
But of course it's your decision. Please discuss internally.

**Comment by petergebruers** [comment]
If this fixes cmake I think it is worth considering. But Justin decides.

**Comment by Oinosseus** [comment]
Well, I think it is not related to cmake. Rferred to my simple example project:

This does not work with OZW:
`g++ -l pthread -lopenzwave main.cpp`

While this does work with OZW:
`g++ -l pthread -lopenzwave -I/usr/local/include/openzwvae/ main.cpp`

It is just the issue that one has to set /usr/local/include/openzwave/ as include path. While /usr/local/include/ is the standard include path.

**Comment by Fishwaldo** [comment]
My big concerns here:
1) it’s breaks the API. Existing Apps and Wrappers have to update to be able to compile after this change. 
2) the changes need to be made to Windows compiles as well. 

Plenty of libraries use a subdir in include or “non-standard” paths to install. That’s what pkg-Config was created. You could install OZW in /a/b/c/d/whoop/waaa and with gcc -I’pkg-config —cflags libopenzwave’ main.cc it should still work. (Sorry can’t find the right backtick on my phone right now but you should get the idea). 

I usually ask people to discuss changes before starting work on things like this as I hate rejecting or wasting people’s time!

**Comment by Fishwaldo** [comment]
> It is just the issue that one has to set /usr/local/include/openzwave/ as include path. While /usr/local/include/ is the standard include path.

Maybe on your system, but on mine:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9
 /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/x86_64-redhat-linux
 /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/backward
 /usr/lib/gcc/x86_64-redhat-linux/9/include
 /usr/include
End of search list.

Not on mine :) (Just pointing out - Portability is a bitch!)

**Comment by petergebruers** [comment]
Nothing gets moved so I don't see how this bewaks the but than can be tested.

But I get your point. I see it this way: the paths in the include files are not relative and this causes a problem when you do not use -I - but the whole problem goes away when you figure out where the library is, and use whatever means (like my workaround for cmake or pkg-config or whatever)

As I understand it... Your main concern is that this PR breaks somenthing and then you have that fix that...

Don't fix it if it aint broken, right?

**Comment by Oinosseus** [comment]
I understand your concerns. At the end it's not a big think, just a small flaw.
Just reject my suggest, I promise not to cry :-)

**Comment by petergebruers** [comment]
> understand your concerns. At the end it's not a big think, just a small flaw.
> Just reject my suggest, I promise not to cry :-)

In all honesty, I am sorry I may have lead to you to believe that this was an easy PR to accept, especially because I pointed out that your first version not every path was fixed...

I think it would help if we would have proper instructions to use OpenZWave from source (either from zip, or as a git subproject incorporated in your project) and by some coincidence I was working on that a little bit before you posted this.

It is possibly also really bad timing, Justin is working hard to get the new "qt-openzwave" (mqtt hass integration) up and running while at the same time more people get bitten by the "interview order bug) see #1981. So on the Dev branch there is a "major rework in progress".

I appreciated your work and I have a copy of your work so we might revisit this, I don't know, there are still a few OZW issues to be solved (cough)...

**Comment by Fishwaldo** [comment]
Closing this for now. Lets consider it for a 1.8 release when API breakages (or compile breakages) can be considered.

**Comment by Oinosseus** [comment]
Hello,

I re-open this issue because I have news. This issue keeps annyoing me when trying to pull the latest ozw project state and compile it with my project.
I created a python script (~100 lines) that automatically scans all ozw source files for relative project includes and corrects them (in the local ozw git checkout).

Could this be of public interest? Maybe other people have this issue too.
I can:
1. upload the script to a separate git project or
1. fork ozw, include the script and create a new pull request
1. distribute the script elsewehere
1. not provide the script and just use it for my own

For sure this pull request needs to stay as "denied" but can you recommend one of the options above?

Thanks,
Thomas

**Pull request closed without merging**
