### PR TITLE
Support for the ZWave.me Z-Uno device

### PR DESCRIPTION
**Pull request by gizmocuz**

### CODE REVIEW

**Comment by Fishwaldo** [comment]
according to #960 we need to use ForceInstances config option?

**Comment by Fishwaldo** [comment]
Hi,
Apologies, I just cleaned up the repo, removing old object files from way back when. This has resulted in PR's being messed up. Could you please redo the PR after pulling a new fork (the repo should be much smaller now though)

Thanks

**Comment by gizmocuz** [comment]
@nechry, this is with the development bootloader, latest version

**Comment by nechry** [comment]
@gizmocuz sorry I did not yet received a Z-uno, I'm supposed to receive one next week. I will enable to do some tests after.

**Pull request closed without merging**
