### PR TITLE
added min dim level config param for WD200 dimmers

### PR DESCRIPTION
**Pull request by jonross09**
tested w/ WD200 dimmer & Home Assistant w/ Aeotec Z-Stick Gen5

### CODE REVIEW

**Comment by petergebruers** [comment]
Thank you for contributing.

I've found a document mentioning this is (a) firmware dependent (b) they've also added "group 2"

https://forums.homeseer.com/forum/homeseer-products-services/homeseer-z-wave-products/homeseer-dimmers-switches/1244903-hs-wd200-and-hs-ws200-firmware-updates

Please add that reference or a reference to this PR when you make a `<ChangeLog>`entry describing your changes.

Can you please add (and test) that group 2 as well and mention the firmware version in the help text eg "min dim level (device firmware >= 5.14)".

Also increase the version number of the xml file, then please run "make xmltest" and commit the changed files, and push them to your master branch to update this PR.

**Comment by jonross09** [comment]
Happy to update the PR to reflect the requested changes.

I don't really know how to add & test "group 2". I don't really know what
that means. Is that a feature or a z-wave command? I know very little about
z-wave, and I'm not looking at the commands going over the air.

I'm testing via updating the xml file in HomeAssistant's docker image, and
just testing in the UI for HomeAssistant. I can tail the z-wave log, but I
don't really know what to look for.

Let me know how to proceed.

Thanks,

-Jon

**Comment by petergebruers** [comment]
> I don't really know how to add & test "group 2". I don't really know what that means. Is that a feature or a z-wave command? I know very little about z-wave, and I'm not looking at the commands going over the air.

Groups aka Associations allows a device, A (your WD200) to control a device B (for example, another dimmer) - without having to write code on a controller. In fact, the controller plays no part in that type of communication. There are pro's and con's.

You didn't tell me what software, so I randomly selected a post on Domoticz to give an example.

https://www.domoticz.com/forum/viewtopic.php?t=9739

I'll keep this PR open for you or someone else to complete the config file.

**Comment by Fishwaldo** [comment]
Closing this.

**Pull request closed without merging**
