### PR TITLE
Updated support for Aeotec NanoMote Quad

### PR DESCRIPTION
**Pull request by zackbcom**
Added support for the 4 buttons.
Source: https://products.z-wavealliance.org/products/2817
https://aeotec.freshdesk.com/support/solutions/articles/6000184697-nanomote-quad-technical-specifications-
https://aeotec.freshdesk.com/support/solutions/articles/6000184696-nanomote-quad-user-guide-

Added support for Config value 41--Enable send central scene notification.
source: https://products.z-wavealliance.org/Products/2817/XML

### CODE REVIEW

**Comment by nechry** [comment]
@zackbcom your change function they on the main branch?
It would be nice to maintain the order of the parameters. The 41 before the 42.

**Comment by zackbcom** [comment]
I will update the order and provide testing results.

**Comment by zackbcom** [comment]
I have ran the XMLtest and have received passing values:
`/home/zackb/github/open-zwave/config/aeotec/zwa003.xml validates
...
No errors detected (You can submit your changes to OZW)
`

**Comment by nechry** [comment]
@zackbcom ok, good always good to run the xmltest before submitting a PR. but my question is more about with which version did you test the config with your device?
On my side the tests were not very successful, but I use another branch than the master

**Comment by zackbcom** [comment]
Let me do some more in-depth testing and when complete, I will post back. I will test with the master branch.

**Comment by zackbcom** [comment]
All seems to be working on master branch. 

- Created a [docker container](https://github.com/ruimarinho/docker-openzwave)
- Updated DockerFile to pull down my branch patch-2
- Started Docker
- Validated that the change I have made were in the container
- Connected my usb device
- Refreshed all data
- Saved the XML on OpenZWave Control Panel
- Checked out the zwcfg_0x<HomeId>.xml file for the updated Central Scene Reports
- Pressed each button on the device.
- Checked logs for correct data.

Logs:
**Button 1**
```
2019-03-06 22:09:58.461 Info, Node053, Received Central Scene set from node 53: scene id=1 in 7680 seconds. Sending event notification.
```

**Button 1 long press:**
```
2019-03-06 22:10:33.988 Info, Node053, Received Central Scene set from node 53: scene id=1 in 7800 seconds. Sending event notification.
2019-03-06 22:10:34.636 Info, Node053, Received Central Scene set from node 53: scene id=1 in 7740 seconds. Sending event notification.
```


**Button 2 Press:**
```
2019-03-06 22:11:55.411 Info, Node053, Received Central Scene set from node 53: scene id=2 in 7680 seconds. Sending event notification.
```


**Button 2 long press:**
```
2019-03-06 22:12:45.949 Info, Node053, Received Central Scene set from node 53: scene id=2 in 7800 seconds. Sending event notification.
2019-03-06 22:12:46.379 Info, Node053, Received Central Scene set from node 53: scene id=2 in 7740 seconds. Sending event notification.
```


**Button 3 Press:**
```
2019-03-06 22:13:38.847 Info, Node053, Received Central Scene set from node 53: scene id=3 in 7680 seconds. Sending event notification.
```


**Button 3 long press:**
```
2019-03-06 22:15:41.574 Info, Node053, Received Central Scene set from node 53: scene id=3 in 7800 seconds. Sending event notification.
2019-03-06 22:15:41.974 Info, Node053, Received Central Scene set from node 53: scene id=3 in 7740 seconds. Sending event notification.
```


**Button 4 Press:**
```
2019-03-06 22:16:23.650 Info, Node053, Received Central Scene set from node 53: scene id=4 in 7680 seconds. Sending event notification.
```


**Button 4 long press:**
```
2019-03-06 22:16:44.547 Info, Node053, Received Central Scene set from node 53: scene id=4 in 7800 seconds. Sending event notification.
2019-03-06 22:16:44.870 Info, Node053, Received Central Scene set from node 53: scene id=4 in 7740 seconds. Sending event notification.
```

**change Setting:**
Not working - removed

### Home Assistant Information:

**Action**|**scene\_id**|**scene\_data**
:-----:|:-----:|:-----:
Button one single tap|1|7680
Button one hold|1|7800
Button one release|1|7740
Button two single tap|2|7680
Button two hold|2|7800
Button two release|2|7740
Button three single tap|3|7680
Button three hold|3|7800
Button three release|3|7740
Button four single tap|4|7680
Button four hold|4|7800
Button four release|4|7740

Example Event:

```yaml
    "event_type": "zwave.scene_activated",
    "data": {
        "entity_id": "zwave.nanomote",
        "scene_id": 2,
        "scene_data": 7680
    }
```

**Comment by zackbcom** [comment]
@nechry Let me know if you need any more information.

**Pull request merged**
