### PR TITLE
Update ZDB5100.xml

### PR DESCRIPTION
**Pull request by staal0**
According to: https://products.z-wavealliance.org/products/3399/configs

### CODE REVIEW

**Review by staal0 — COMMENTED** [review]
According to: https://products.z-wavealliance.org/products/3399/configs

**Comment by staal0** [comment]
@Fishwaldo - Question:  Device gets recognized as switch not as dimmer. Is it possible to ajust this in the xml? or is this device one of the 2-3% using non-standard implementation?

**Comment by kpine** [comment]
> Question: Device gets recognized as switch not as dimmer

What's the context here? You don't see the dimmer command classes (multilevel switch) reported by the device, or your home automation software doesn't show it as a light?

**Comment by staal0** [comment]
Home Assistant sees it as a switch - if generic value is changed from 24 (switch) to 17 (dimmer) inside the node tag it will become a dimmer. So my question is, if I can change anything in the xml to make it get recognized as a dimmer?

**Comment by kpine** [comment]
> if generic value is changed from 24 (switch) to 17 (dimmer) inside the node tag it will become a dimmer.

You should submit an issue to the HA core project to support this. It's not changed in the XML.

**Comment by staal0** [comment]
Yes, that sounds right - I thought that might be the case. It's been far too long since I've looked at this integration. I'll submit an issue to HA.

**Pull request merged**
