### PR TITLE
Continuation of Improve support for CentralScene Command Class

### PR DESCRIPTION
**Pull request by robbiet480**
Continuing PR #993

### CODE REVIEW

**Comment by nechry** [comment]
@robbiet480 do you already take a look this jeedom implementation in beta branch?
https://github.com/jeedom/plugin-openzwave/blob/beta/resources/python-openzwave/openzwave/cpp/src/command_classes/CentralScene.cpp

**Comment by robbiet480** [comment]
@nechry Yup, but hadn't taken a close look at the differences between the jeedom branch and @tobiasgraf's code. Do you think yours is a better base to work from?

**Comment by nechry** [comment]
We expose more possibilities, like "Scene Number" see comment of @stromnet 
https://github.com/OpenZWave/open-zwave/pull/993#issuecomment-274277201

I don't want said the @tobiasgraf's work is not good, but we must consider to keep all good parts (implementation) for both side.

**Comment by robbiet480** [comment]
@nechry I'll go ahead and re-stage this PR with your code as a base.

**Pull request closed without merging**
