### PR TITLE
Update according to latest spec

### PR DESCRIPTION
**Pull request by ericstaal**
Spec: https://www.benext.eu/static/manual/energyswitchrs.pdf

A lot of config items where missing. I have added them

### CODE REVIEW

**Comment by nechry** [comment]
this config file is shared with 3 devices ids different. We must be sure this PR is for all.

**Comment by nechry** [comment]
the initial commit target
https://github.com/OpenZWave/open-zwave/commit/e9b0c7f891ab5456c1e6aa8e51ce7e3e762c9f1e#diff-90e529806c85d119687dec7b42c6315f
Product type="0006" id="0101"

is possible your PR target the new version

**Comment by Fishwaldo** [comment]
ping!

**Comment by Fishwaldo** [comment]
Closing

**Pull request closed without merging**
