### PR TITLE
Create zen34.xml

### PR DESCRIPTION
**Pull request by hoopsta1423**
add zen34 config file

### CODE REVIEW

**Review by hoopsta1423 — COMMENTED** [review]
updated line 49

**Review by hoopsta1423 — COMMENTED** [review]
removed png reference - not available yet

**Review by hoopsta1423 — COMMENTED** [review]
added productpic metadata

**Comment by cybergrimes** [comment]
I just came by to submit this myself, is there an updated manufacturer_specific.xml too?

**Comment by hoopsta1423** [comment]
> I just came by to submit this myself, is there an updated manufacturer_specific.xml too?

Embarrassingly no...this is my first PR so I couldn't figure out how to get them both in one...

**Comment by cybergrimes** [comment]
Try forking the OZW project, changing/creating all files in the fork then do a pull request of the whole fork. It should capture all the different files into one commit. I don't know if there's another way but that method has worked for me.

**Pull request closed without merging**
