### PR TITLE
Add configuration for HomeSeer HS-WD100+ Wall Dimmer

### PR DESCRIPTION
**Pull request by sterling**

### CODE REVIEW

**Comment by nechry** [comment]
You sure about size of parameter 10?

**Comment by nechry** [comment]
A param 7 and 8 are also supposed to exists.
The 10 is a byte and accept 1 to 255, not a list.

**Comment by sterling** [comment]
I referenced http://products.z-wavealliance.org/products/1730/configs for the parameters. Using this configuration appears to work locally.

**Comment by nechry** [comment]
Ok if you have validate a change with the parameters 10 and the device accept it, is the answer.

**Comment by nechry** [comment]
Thanks @sterling

**Pull request merged**
