### PR TITLE
New Sensor, and updated sensor

### PR DESCRIPTION
**Pull request by DeviantEng**
Added Zooz ZEN15 config.

Update Zooz ZSE40 config to reflect the new version of this sensor, even though it has the same product type and ID.  The vendor sent me a sample to test with along with parameter documentation.  Parameters have changed slightly, but the Product Type and ID has changed so I updated the config for the latest version.

### CODE REVIEW

**Comment by nechry** [comment]
please always run make xmltest before submit config PR

/root/open-zwave/config/zooz/zen15.xml:7: element Value: Schemas validity error : Element '{http://code.google.com/p/open-zwave/}Value', attribute 'vindex': The attribute 'vindex' is not allowed.
/root/open-zwave/config/zooz/zen15.xml:12: element Value: Schemas validity error : Element '{http://code.google.com/p/open-zwave/}Value', attribute 'vindex': The attribute 'vindex' is not allowed.
/root/open-zwave/config/zooz/zen15.xml:18: element Value: Schemas validity error : Element '{http://code.google.com/p/open-zwave/}Value', attribute 'vindex': The attribute 'vindex' is not allowed.
/root/open-zwave/config/zooz/zen15.xml:24: element Value: Schemas validity error : Element '{http://code.google.com/p/open-zwave/}Value', attribute 'vindex': The attribute 'vindex' is not allowed.

**Comment by nechry** [comment]
And
Errors: (Please Correct before Submitting to OZW)
config/zooz/zen15.xml: Parameter: 152 The size is wrong for a int - Error Code 2

**Comment by nechry** [comment]
I already fix all of them.

**Comment by DeviantEng** [comment]
Sorry about that.  I was provided that zen15.xml and didn't write it myself, so I didn't look over it well enough.  Thanks for the catching that and fixing!

**Comment by nechry** [comment]
no problem. I report for your information.

**Pull request merged**
