### PR TITLE
Device Support: Multisensor 6 config update

### PR DESCRIPTION
**Pull request by shanemadden**
Updated config parameters for Multisensor 6, using the [most recent reference material I've been able to find.](https://github.com/robertvandervoort/SmartThings/blob/master/Aeon%20Multisensor%206/Engineering%20Spec%20-%20Aeon%20Labs%20MultiSensor%206.pdf)

 - Param 3: 
   - Make it clear that this is for motion specifically, not any other kinds of wake-up.
   - Clarify the round-up behavior a little, hopefully.
 - Param 40:
   - Causes reporting only when thresholds are hit, as opposed to enabling threshold based reporting. Made that a little clearer.
 - Param 41-44:
   - Update units, sizes, and defaults.
 - Param 101-103:
   - Update help on the bitmask to make the numbers clearer.
 - Param 111-113:
   - Updated to accurately reflect the two different behaviors for these params based on the device's power source (and added a comment on how to tell from the application side which power source the device is on)

### CODE REVIEW

**Comment by nechry** [comment]
most of you patch are include in pending PR https://github.com/OpenZWave/open-zwave/pull/779/commits/ab405fb550cfbf6683819d3cbab61cabd81475e1
Il also found a new issue in aeon-labs doc for param 42
https://github.com/jeedom/plugin-openzwave/commit/e693018cdeb2273a22b448c4e021da5d1d5a5ef8
size is 1 but tell is 2. 

But your PR is good for my point of view, precisely the help clarification.

**Comment by shanemadden** [comment]
@nechry Thanks for pointing that out, I didn't see that pending PR! I can plan on re-applying the help text changes once that's been merged.

**Comment by nechry** [comment]
cool, and I will also rename all Aeon-labs devices after the PR and your merge.
see: https://groups.google.com/forum/#!topic/openzwave/zLZFQrihhDs

**Comment by Fishwaldo** [comment]
Just FYI....
The Jeedom PR is in progress. I'll hopefully merge it this week. 

Sent from my iPhone

On 23 Mar 2016, at 1:06 AM, Jean-Fran?ois Auger <notifications@github.com <mailto:notifications@github.com> > wrote:

cool, and I will also rename all Aeon-labs devices after the PR and your merge.
see: https://groups.google.com/forum/#!topic/openzwave/zLZFQrihhDs

**Comment by shanemadden** [comment]
@Fishwaldo Great, thanks! I'll get this PR updated once that's merged.

**Comment by Fishwaldo** [comment]
@shanemadden The Jeedom PR is merged. Please update when ready.

**Comment by nechry** [comment]
@shanemadden @Fishwaldo  I do a big renaming in aeon-labs devices family. 
see: https://github.com/jeedom/plugin-openzwave/commit/ff6849a88e2144fe44530400a2c74228e9251b58

this commit contains also many missing config and fix default values.

I think it will be more easy wait again, we push there updates and after apply your nice bit mask approach.

I will check to create a PR a soon a possible with @sarakha63

**Comment by shanemadden** [comment]
Merged up to current master; happy to wait and do so again once the renames are merged!

**Comment by Fishwaldo** [comment]
@nechry I'll leave this to you.

**Comment by nechry** [comment]
@shanemadden hello, the big renaming and merge is done. if you still want apply your changes to the new file. the Multisensor 6 file is now:
https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/zw100.xml

**Comment by shanemadden** [comment]
@nechry Great, thanks! I'll find some time to rebase and retest in the next few days.

**Comment by Fishwaldo** [comment]
Please open a new PR when ready.

**Pull request closed without merging**
