### PR TITLE
Adding KeyWe

### PR DESCRIPTION
**Pull request by crxrocks**
Adding KeyWe

### CODE REVIEW

**Comment by crxrocks** [comment]
Adding KeyWe

**Comment by crxrocks** [comment]
Hopefully this works.  :)

**Comment by nechry** [comment]
can you add a specific config with association group definition and link to product https://products.z-wavealliance.org/products/2905

**Comment by crxrocks** [comment]
@nechry  - I'm sorry to be a pain, but I'm not sure how to even start w/ that.  This is my first time adding anything for ZWave.  Is there a wiki that I missed with an example of how it is done?

**Comment by nechry** [comment]
@crxrocks yes https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by crxrocks** [comment]
Sorry guys, I'm not smart enough to do this apparently.  I reached out to KeyWe hoping they would do it, but they stated they don't support Open Zwave, which is stupid.

**Pull request closed without merging**
