### PR TITLE
Adding support for Namron Z-Wave 4-Channel Wall Remote K8

### PR DESCRIPTION
**Pull request by plheide**

### CODE REVIEW

**Comment by nechry** [comment]
you remove 2 xml elements, is more a purge.

**Comment by plheide** [comment]
Line 85, 89 and 90 in `config/device_configuration.xsd` are duplicates (invalid XML) and cause XML validation to fail.

**Comment by nechry** [comment]
yes I just check the resumed view without full file. I will merge soon

**Comment by plheide** [comment]
Great! :+1:

**Pull request merged**
