### PR TITLE
Added config for Ecolink FLF-ZWAVE5 Flood/Freeze sensor

### PR DESCRIPTION
**Pull request by dhylands**
This adds config support for the Ecolink FLF-ZWAVE5 Flood/Freeze sensor.

In particular it uses the SensorMap feature to allow the Freeze sensor to be detected, since this is only reported on the SENSOR_BINARY command class.

Tested on master. The Dev branch doesn't seem to have the SensorMap support, so I was only able to verify that the Dev branch behaved as before.

xmltest passed.

### CODE REVIEW

**Comment by dhylands** [comment]
Bumped the revision number in manufacturer_sepcific.xml. This wasn't mentioned on the https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices wiki page.

**Comment by petergebruers** [comment]
Please give me push rights, files have been edited in parallel... Or merge master + bump manufacturer_sepcific.xml + run make xmltest then push changes

**Comment by dhylands** [comment]
rebased against latest master - and bumped manufactuer_sepcific.xml revision again

**Comment by petergebruers** [comment]
Thanks!

**Pull request merged**
