### PR TITLE
Fix of bug #1474 (Color class didn't work anymore on zipato bulb 2)

### PR DESCRIPTION
**Pull request by jeroenst**

### CODE REVIEW

**Comment by nechry** [comment]
the zipato bulb 2 work without this change. and set the channel in config will not apply to the device. this PR seem invalid for my point of view,

**Comment by gizmocuz** [comment]
I can confirm it works here to without this patch

**Comment by jeroenst** [comment]
Possible you have newer firmware in your bulb. The bug is fixed in later firnware zipato told me. But afaik it is not possible to update firmware with openzwave

**Comment by BramJ85** [comment]
My 3 Zipato Bulb2's showed no RGBW control (in Domoticz), adding the changes described by @jeroenst to my RGBBulb2.xml fixed my issues 

maybe this issue should be looked at again?

**Comment by blintwave** [comment]
Think it has something to do within Domoticz, running Hass.io i have no problems with Zipato bulb 2 only that i have to restart the instance  a few times to get colors to work but after that it works without any issues. I even have tested this bulb with Openhab and everything works except that dimming sometimes works unexpected. So I think it depends how some domotica software implents openzwave in their own instance, but currently from my point of view this bulb works the best with home assistant.

**Comment by gizmocuz** [comment]
I tested with domoticz and have no issued to use the Zipato Bulb version 2

**Comment by blintwave** [comment]
Out of the box? Or edited with RGBBulb2.xml?

**Comment by BramJ85** [comment]
On another forum I found some people with the same problem as me, at least one fixed it with the editied xml.

@jeroenst mentioned that Zipato said something about diffirent firmware versions? is there a way to figure out what firmware version is in the bulb?

**Comment by voggur** [comment]
Hi I recently got my fist smart-home appliance and dust got two Zipato bulb 2 Model "rgbw2.eu" datecode "1807" and I can not get it do anything other than on/off and dimm. I have tried editing RGBBulb2.xml with no luck

**Pull request closed without merging**
