### PR TITLE
Request to add support for Philio PAN06

### PR DESCRIPTION
**Pull request by allan-gam**
Adding support for Philio PAN06

### CODE REVIEW

**Comment by rrozema** [comment]
Option 4 says in the help "0 disables", however min value is 1. So the user can not disable auto off using this settings file?

**Comment by allan-gam** [comment]
According to the [PAN06-1A manual](https://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/1181/PAN06-1A%20manual-20141118.pdf) valid values for parameter 4 are 0 to 0x7FFF. Where does it say that min value is 1?

**Comment by rrozema** [comment]
line 27: <Value type="short" genre="config" instance="1" index="4" label="4. Auto off time: 0=Disable,  1s ~ 32767s delay" **min="1"** max="32767" value="0">

**Comment by nechry** [comment]
Please remove numbers in labels and also the label must be simplified, use the help element for explanation

**Comment by rrozema** [comment]
I agree that there is to much text in the labels that should be moved into a help element. However i -as a beginner user- personally like having the index number in the label as this is often also how it"s presented in the device's manual. Having the index number onscreen makes it a lot easier to match the screen with the instructions in the manual.

**Comment by allan-gam** [comment]
Having a closer look at the text, I found it necessary to make a total overhaul of the labels and help texts except for the last item "Existence of endpoint 3 Action" (I'm unable to grasp what it's about) The original text seems to be fetched from the user manual and it kind of "cheesy" mildly put. It took me a while to actually understand what they meant.

Doing this, makes it look a bit different from the users manual but hopefully it's more understandable. What do you guys think?

**Comment by nechry** [comment]
@rrozema recall the parameter index number must be perform by your gateway UI. 
Like this for exemple:
paramters

**Comment by nechry** [comment]
@allan-gam auto="false" is only for group 1, auto="true" is accepted for other groups if required.
most of time group 1 is for Lineline and we must add the primary controller, others groups are in general for directs associations

**Comment by nechry** [comment]
@allan-gam if you run a ```make xmltest``` all errors will be reported, is a good habit before submit a PR. I fixed the PR

**Comment by allan-gam** [comment]
Thank you @nechry

**Pull request merged**
