### PR TITLE
Eurotronic Spirit Z

### PR DESCRIPTION
**Pull request by tobiasgraf**
Adds config files for The Eurotronic Spirit Z Thermostat.

Thanks @epegzz for the improvements and all the others for the reviews and testing.

see #1341 

This requires on #1385 and #1386

### CODE REVIEW

**Comment by Fishwaldo** [comment]
The dev branch has a new format for config files. (slight changes only) so this will not work. Take a look at aeotec/zw100.xml as a example.

**Comment by twendt** [comment]
@Fishwaldo Can you point to where the changes are needed? I have this config working with the Dev branch.
I looked at zw100.xml, but I do not see where the changes in the format are.

**Comment by nau-mll** [comment]
Hi all, does anyone know if adding such changes to latest installed release would work? Or shall I better compile & install a new version out of this branch?

**Comment by EyMaddis** [comment]
@Fishwaldo It seems that @diman1234 did the update. Can you confirm and merge?

**Comment by EyMaddis** [comment]
By the way, I use this branch and it is working just fine

**Comment by psorobka** [comment]
Confirmed - it works very well.

**Comment by RobKuipers** [comment]
Check - works like a charm!

**Comment by 1ne8ight7even** [comment]
When can we expect this pull request gets merged?

**Pull request merged**
