### PR TITLE
Support for Qubino 3-phase meter

### LINKED ISSUE #1498: Config file "draft" for Qubino ZMNHXDx 3-Phase Smart Meter
Hi all,

I have initiated the creation of a config file for the fantastic new ZMNHXDx but as I'm just a simple user I call out for some help... anyone? :-)

To make it easier for me I modified the 1-Phase Meter .xml and some additional config is left in the second half of the file, i.e. read out device serial number etc. but it seems not get any data from the 3-Phase version. So if I did not do this part obvious wrong it should most likely be removed for this model. 

Cheers!

 //Ricard

[Qubino_ZMNHXDx_3-Phase_Smart_Meter.zip](https://github.com/OpenZWave/open-zwave/files/1972278/Qubino_ZMNHXDx_3-Phase_Smart_Meter.zip)

### PR DESCRIPTION
**Pull request by cincuranet**
Support for Qubino 3-phase meter. [Manual][1].

I'm not sure about the `<CommandClass id="142" ForceInstances="true" />` and `<CommandClass id="96" mapping="endpoints" />`. With those the device seems to work best. Without the _96_ it does not properly report some values (and there's 5 instances then; and something like "previous value" is then available for i.e. `Total kWh`; confusing). 😕 Seems like Qubino devices are somewhat specific. Maybe somebody can comment. I'm ready to test it as much as possible.

The result in OZW's Control Panel is then this:
ozw-cp

Which looks good-ish to me. The last _Unknown_ value I think is _var_. Can I somehow provide name for it? Not sure what the the remaining 3 _Unknown_ values on top are. Looks like something per-phase (see below), maybe `kWh` based on the `index`, weird it's `0.0`.

The `COMMAND_CLASS_METER` command class (empty lines mine for readability):

```xml
<CommandClass id="50" name="COMMAND_CLASS_METER" version="4" request_flags="3" innif="true">
    <Instance index="1" endpoint="1" />
    <Instance index="2" endpoint="2" />
    <Instance index="3" endpoint="3" />
    <Instance index="4" endpoint="4" />
    
    <Value type="decimal" genre="user" instance="1" index="0" label="Energy" units="kWh" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="1" index="4" label="Energy" units="kVAh" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="1" index="8" label="Power" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="2458.4" />
    <Value type="decimal" genre="user" instance="1" index="24" label="Power Factor" units="Power Factor" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.7671" />
    <Value type="decimal" genre="user" instance="1" index="28" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="-140.0" />
    <Value type="bool" genre="user" instance="1" index="32" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
    <Value type="button" genre="system" instance="1" index="33" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
    
    <Value type="decimal" genre="user" instance="2" index="0" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="2" index="8" label="Power" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="240.5" />
    <Value type="decimal" genre="user" instance="2" index="16" label="Voltage" units="V" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="242.7" />
    <Value type="decimal" genre="user" instance="2" index="20" label="Current" units="A" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.407" />
    <Value type="decimal" genre="user" instance="2" index="24" label="Power Factor" units="Power Factor" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.5604" />
    <Value type="bool" genre="user" instance="2" index="32" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
    <Value type="button" genre="system" instance="2" index="33" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
    
    <Value type="decimal" genre="user" instance="3" index="0" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="3" index="8" label="Power" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="64.0" />
    <Value type="decimal" genre="user" instance="3" index="16" label="Voltage" units="V" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="239.8" />
    <Value type="decimal" genre="user" instance="3" index="20" label="Current" units="A" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.583" />
    <Value type="decimal" genre="user" instance="3" index="24" label="Power Factor" units="Power Factor" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.8819" />
    <Value type="bool" genre="user" instance="3" index="32" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
    <Value type="button" genre="system" instance="3" index="33" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
    
    <Value type="decimal" genre="user" instance="4" index="0" label="Unknown" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0" />
    <Value type="decimal" genre="user" instance="4" index="8" label="Power" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="169.8" />
    <Value type="decimal" genre="user" instance="4" index="16" label="Voltage" units="V" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="241.7" />
    <Value type="decimal" genre="user" instance="4" index="20" label="Current" units="A" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.904" />
    <Value type="decimal" genre="user" instance="4" index="24" label="Power Factor" units="Power Factor" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.7814" />
    <Value type="bool" genre="user" instance="4" index="32" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
    <Value type="button" genre="system" instance="4" index="33" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0" />
</CommandClass>
```

Also resolves #1498.

[1]: http://qubino.com/download/2244/

### CODE REVIEW

**Comment by nechry** [comment]
I think the 3 Unknown values on top are created with this line https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/command_classes/Meter.cpp#L560
the last Unknown can be the kVar base on the https://www.silabs.com/documents/login/miscellaneous/SDS13781-Z-Wave-Application-Command-Class-Specification.pdf
table 67 page 296. This value is relative to Meter v4

**Comment by nechry** [comment]
thank @cincuranet

**Comment by cincuranet** [comment]
ad kVar> Could be. I'll check with the display later today. Looking into the PDF, wondering where is the kVarh then?

Also I'm not sure about the "Previous Meter Value" values. If I omitted the above mentioned _142_ and _96_ I saw fields that looked like previous values for i.e. kWh, but the updating was not working properly and there were 5 instances. :( 

Any idea how to check what is actually sent/supported by the meter?

**Comment by laurisvr** [comment]
Hello, I have included this module as well, but I'm having issues with that only the power consumption values seem to update. I am using home assistant. Does anyone have this issue as well or know a possible cause?

**Comment by laurisvr** [comment]
@cincuranet When comparing your COMMAND_CLASS_METER with mine I noticed that your kWh value is also 0, even though the consumption is rather high. Is this value updated properly for you?

**Comment by laurisvr** [comment]
Okay, this seems to have been fixed by upgrading to the latest version of open z wave. It also doesn't help it updates so infrequently:)

**Pull request merged**
