### PR TITLE
Create ms11z.xml

### PR DESCRIPTION
**Pull request by rjmcfadd**
Add MS11Z Dimmer switch

### CODE REVIEW

**Comment by nechry** [comment]
@rjmcfadd please fix tests failure

**Review by rjmcfadd — COMMENTED** [review]
Sorry, the formatting got messed up after pasting it.

**Comment by nechry** [comment]
close the `<Product>` element and if you cal also add the `<MetaData>` section as describe https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by nechry** [comment]
great, thank @rjmcfadd

**Pull request merged**
