### PR TITLE
Add support for ThermostatMode V3

### PR DESCRIPTION
**Pull request by tobiasgraf**
Adds new thermostate modes introduced with V2 and V3: Full Power and Manufacturer_Specific

see #1341

### CODE REVIEW

**Comment by reimerm** [comment]
Hi @tobiasgraf, not sure if you updated something in between #1341 and this PR but with #1341 patched into master everything works besides the log throwing:

`2017-12-06 15:52:04.894 Info, Node002, Response RTT 192 Average Response RTT 192
2017-12-06 15:52:04.894 Info, Node002, Received **unknown** thermostat mode: **index 15**
2017-12-06 15:52:04.895 Detail, Node002,   Expected reply and command class was received
2017-12-06 15:52:04.895 Detail, Node002,   Message transaction complete`

**Comment by tobiasgraf** [comment]
Are you sure you are using this correct? The changes to ThermostatMode are the same in both PRs.
Did you reinclude the device with this (and the other 2) PRs?

**Comment by Fishwaldo** [comment]
Thanks

**Comment by sjabby** [comment]
I think there is a bug with this ? https://github.com/OpenZWave/open-zwave/issues/1398

**Pull request merged**
