### PR TITLE
Added Philio PSP05-D Motionsensor Outdoor

### PR DESCRIPTION
**Pull request by superjunky**
Tested.

I'm new to github, so bare with me if I make any mistakes. Advice me if needed.

### CODE REVIEW

**Comment by nechry** [comment]
please check my last commit
https://github.com/OpenZWave/open-zwave/commit/cc0c4ee09f96fc5219ae85c5768987c862a22561.
I think you reuse a other config file as master?

**Comment by superjunky** [comment]
Yes, thanks @nechry .

I'm not sure how to link to a line, but I suggest to not remove line 49. For the same reason it was added to other Philio motion sensors. It helped me out configuring the device.

**Comment by nechry** [comment]
ok but the default value is not 22, only recommended value?

**Comment by nechry** [comment]
with default value no binary report?

**Comment by superjunky** [comment]
Yes, the default value is 4

**Comment by nechry** [comment]
yes the 00010110 (22) seem good configuration

**Comment by superjunky** [comment]
The original setting of the device is 4 according to the documentation. But it made no sense in ozw..
I prefer 22 as default, but other Philio devices have it set at 4. It's up to you ;)

**Comment by nechry** [comment]
ok good I restore the ozw recommended setting. 
I have also rename the config, this config are shared with 3 version B C and D.

**Comment by nechry** [comment]
We must set the real default config value in xml file, is the internal value store in device. If the documentation said 4 we must wrote 4. but yes I use the comment to provide help for ozw usage

**Comment by nechry** [comment]
I jeedom gateway we have recommended setting during the post inclusion process. and I set all recommended values for users

**Comment by nechry** [comment]
If you set a wrong default value (not the one defined) your device will report this value as the current. but internal the real default value still set. with your config (default set to 22) users thing it's the real value and they will not change to get the device working and they will not understand.

**Comment by superjunky** [comment]
Thanks for the advice. Will use it for future reference.

**Comment by nechry** [comment]
you welcome, and happy to get a new contributor

**Pull request merged**
