### PR TITLE
Fibaro FGWR111 Walli Roller Shutter 

### PR DESCRIPTION
**Pull request by khashayar**
Followings have been done:

- Added Fibaro Walli Roller Shutter to `manufacturer_specific.xml` file.
- Created `fgwr111.xml` config file.
- Ran the xml test and bumped up the version.

### CODE REVIEW

**Comment by khashayar** [comment]
I just noticed that the branch ran into conflict because of another PR got merged into master and bumped the main version. I can resolve the conflict but it can happen again, so please just let me know exactly before you're about to accept this PR and I can take care of it to make sure it doesn't happen again... or kindly do it yourself 😊

**Comment by petergebruers** [comment]
Thanks. Yes, that happens, I'll merge another one today and I'll fix the conflicts and update as needed.

**Comment by petergebruers** [comment]
Ah, can you please "Allow edits from maintainers" on your branch? I'd like to push a few files...

**Comment by khashayar** [comment]
Done!

**Comment by petergebruers** [comment]
Thanks. Going to merge!

**Pull request merged**
