### PR TITLE
Add support for Inovelli lzw36 fan-switch combo

### PR DESCRIPTION
**Pull request by DelusionalAI**
Files pulled right from manufacturers "How to install this device in Home Assistant" config files, with the static central scene reports removed for OZW 1.6. 
https://community.inovelli.com/t/lzw36-openzwave-beta-scene-issues/4010

### CODE REVIEW

**Comment by DelusionalAI** [comment]
File should be ready.. but I'm not sure why xmltest reports no changelog.

**Comment by SirDeadlystrike** [comment]
Looks like we still need the image.

**Comment by Fishwaldo** [comment]
Thanks! I'll bump revision numbers later.

**Comment by SirDeadlystrike** [comment]
@Fishwaldo would you like another PR with the image added for this device?

**Comment by Fishwaldo** [comment]
It's pointing to the wrong image? If so, yes please!

**Pull request merged**
