### PR TITLE
Added support for Schlage Connect BE469NXCEN Touchscreen Deadbolt

### PR DESCRIPTION
**Pull request by rushidesai**
This is based on the config for Assa Abloy's Yale Real Living Cap-Touch Deadbolt type="0002" id="0000".

### CODE REVIEW

**Comment by Fishwaldo** [comment]
You have tested it?

**Comment by rushidesai** [comment]
Yes. I have one of these locks:
http://www.amazon.com/dp/B00AGK9KJG/ref=sr_ph_1?m=ATVPDKIKX0DER&ie=UTF8&qid=1437152413&sr=1&keywords=schlage+deadbolt+touchscreen

**Comment by Fishwaldo** [comment]
I've taken the config changes, but not the Static Library changes (as typically, you don't install static libraries)

**Comment by openzwave-dev-watcher** [comment]
The lock status is inverted for me.  When it's open it shows closed and 
vice-a-versa.

**Comment by openzwave-dev-watcher** [comment]
Any thoughts from the logs?

**Pull request closed without merging**
