### PR TITLE
[RFC] MultiInstanceAssociation support

### PR DESCRIPTION
**Pull request by xs4**
continuation of #560, rebased to New-CC branch

### CODE REVIEW

**Comment by Fishwaldo** [comment]
Build Failure on Windows:
http://bamboo.my-ho.st/bamboo/download/OZW-OZWWXP2-JOB1/build_logs/OZW-OZWWXP2-JOB1-4.log (ignore the Color.cpp warnings - thats my issue to deal with)

**Comment by Fishwaldo** [comment]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(185): error C2440: 'initializing' : cannot convert from 'std::_Tree_iterator<_Mytree>' to 'std::_Tree_iterator<_Mytree>' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(185): error C2678: binary '!=' : no operator found which takes a left-hand operand of type 'std::_Tree_iterator<_Mytree>' (or there is no acceptable conversion) [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(211): error C2440: 'initializing' : cannot convert from 'std::_Tree_iterator<_Mytree>' to 'std::_Tree_iterator<_Mytree>' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(211): error C2678: binary '!=' : no operator found which takes a left-hand operand of type 'std::_Tree_iterator<_Mytree>' (or there is no acceptable conversion) [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(213): error C2146: syntax error : missing ')' before identifier 'and' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(213): error C2059: syntax error : ')' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(214): error C2143: syntax error : missing ';' before '{' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(213): error C3861: 'and': identifier not found [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(366): error C2440: 'initializing' : cannot convert from 'std::_Tree_iterator<_Mytree>' to 'std::_Tree_iterator<_Mytree>' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(366): error C2678: binary '!=' : no operator found which takes a left-hand operand of type 'std::_Tree_iterator<_Mytree>' (or there is no acceptable conversion) [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(409): error C2440: 'initializing' : cannot convert from 'std::_Tree_iterator<_Mytree>' to 'std::_Tree_iterator<_Mytree>' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(409): error C2678: binary '!=' : no operator found which takes a left-hand operand of type 'std::_Tree_iterator<_Mytree>' (or there is no acceptable conversion) [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(439): error C2440: 'initializing' : cannot convert from 'std::_Tree_iterator<_Mytree>' to 'std::_Tree_iterator<_Mytree>' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(439): error C2678: binary '!=' : no operator found which takes a left-hand operand of type 'std::_Tree_iterator<_Mytree>' (or there is no acceptable conversion) [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(462): error C2440: 'initializing' : cannot convert from 'std::_Tree_iterator<_Mytree>' to 'std::_Tree_iterator<_Mytree>' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(462): error C2678: binary '!=' : no operator found which takes a left-hand operand of type 'std::_Tree_iterator<_Mytree>' (or there is no acceptable conversion) [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(464): error C2146: syntax error : missing ')' before identifier 'and' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(464): error C2059: syntax error : ')' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(465): error C2143: syntax error : missing ';' before '{' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(464): error C3861: 'and': identifier not found [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(486): error C2440: 'initializing' : cannot convert from 'std::_Tree_iterator<_Mytree>' to 'std::_Tree_iterator<_Mytree>' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(486): error C2678: binary '!=' : no operator found which takes a left-hand operand of type 'std::_Tree_iterator<_Mytree>' (or there is no acceptable conversion) [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(488): error C2146: syntax error : missing ')' before identifier 'and' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(488): error C2059: syntax error : ')' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(489): error C2143: syntax error : missing ';' before '{' [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]
build	20-May-2015 00:36:24	  ..\..\..\src\Group.cpp(488): error C3861: 'and': identifier not found [E:\bamboo-agent-home\xml-data\build-dir\OZW-OZWWXP2-JOB1\cpp\build\windows\vs2010\OpenZWave.vcxproj]

**Comment by xs4** [comment]
I will try to look into the windows issue, but I am not sure if I will get very far without windows....

**Comment by Fishwaldo** [comment]
maybe its a c++09 versus c++11 issue?

**Comment by Fishwaldo** [comment]
or: http://stackoverflow.com/questions/9791840/stdsetiterator-conversion-error

**Pull request merged**
