### PR TITLE
implemented CRC16Encap support

### PR DESCRIPTION
**Pull request by xs4**
Implemented CRC16Encap support based on the CRC-CCITT algorithm.

### CODE REVIEW

**Comment by Fishwaldo** [comment]
Which Devices are actually using the CEC16Encap? I've seen it appear on NIF frames, but never actually seen it in use.

**Comment by xs4** [comment]
The BeNext Heating control (http://www.benext.eu/producten/heating-control/) uses the CEC16Encap.
I used that device during development and testing. 

(From what I read on the openhab mailing list the fibaro smoke sensor fgss001 also uses the CEC16Encap. see https://groups.google.com/forum/#!topic/openhab/xg_j2tyGwLc )

**Comment by killercode** [comment]
NorthQ also uses it

**Comment by Fishwaldo** [comment]
Merged. Thanks

**Pull request merged**
