### PR TITLE
make xmltest: fix inconsistent storage of revision (int vs string)

### PR DESCRIPTION
**Pull request by petergebruers**
Before this commit, testconfigversions.cfg would sometimes store revision as a string, sometimes as an integer

'config/2gig/ct100.xml' => {
    'Revision' => '6',

After this commit, its always an integer

'Revision' => 6,

Also: bump spec file, run dist-update

### CODE REVIEW

**Comment by petergebruers** [comment]
@Fishwaldo I am not in a hurry, so just checking... Any objection if I merge this one?

**Comment by Fishwaldo** [comment]
Yep. Please merge! I would but there is a merge conflict. 😜

**Comment by petergebruers** [comment]
> I would but there is a merge conflict. 😜

LOL

**Comment by Fishwaldo** [comment]
👍👍

**Pull request merged**
