### PR TITLE
Create config for Steinel RS LED D2 Z-Wave

### PR DESCRIPTION
**Pull request by CookieMonster87**

### CODE REVIEW

**Comment by nechry** [comment]
can you add the link with manufacturer_specific.xml matching type and id

**Comment by CookieMonster87** [comment]
Did forget that.

<ManufacturerSpecificData>
  <Manufacturer id="0271" name="Steinel">
    <Product type="0001" id="1a74" name="RS LED D2 Z-Wave" config="steinel/rs-led-d2.xml"/>
  </Manufacturer>
</ManufacturerSpecificData>

**Comment by CookieMonster87** [comment]
`<ManufacturerSpecificData>
  <Manufacturer id="0271" name="Steinel">
    <Product type="0001" id="1a74" name="RS LED D2 Z-Wave" config="steinel/rs-led-d2.xml"/>
  </Manufacturer>
</ManufacturerSpecificData> `

**Comment by nechry** [comment]
Can you completed  the PR?

**Comment by CookieMonster87** [comment]
First time i create a PR. Is it correct now? :)

**Pull request merged**
