### PR TITLE
Configs for Remotec ZTS-110 thermostat.

### PR DESCRIPTION
**Pull request by gwmullin**
Values (and as much as possible descriptions) pulled from the manual from the manufacturer: https://www.remotec.com.hk/wp-content/uploads/2015/12/8031_V3.12_F820-8031-0004_40p_20140702.pdf

### CODE REVIEW

**Comment by raym777** [comment]
Hi, I came here to request config for this device too :)

Two comments based on my testing:

1. "init" seems to work in my case

2. I have added the following which defines the available modes. 

	<CommandClass id="64" name="COMMAND_CLASS_THERMOSTAT_MODE" version="1" request_flags="4" create_vars="true">
		<Value type="list" genre="user" instance="1" index="0" label="Mode" units="" read_only="false" write_only="false" min="0" max="0" value="0">
			<Item label="Off" value="0" />
			<Item label="Heat" value="1" />
			<Item label="Cool" value="2" />
			<Item label="Auto" value="3" />
		</Value>
		<SupportedModes>
			<Mode index="0" label="Off" />
			<Mode index="1" label="Heat" />
			<Mode index="2" label="Cool" />
			<Mode index="3" label="Auto" />
		</SupportedModes>
	</CommandClass>

Can this be added too please?

3. During initialisation, there are 2 exceptions thrown for unhandled classes but this doesn’t appear to affect the general operation of the device. i.e.:

OpenZWave: Unhandled class: 0x42 (THERMOSTAT OPERATING STATE), NodeID: 9 (0x09), Index: 0, Instance: 1

OpenZWave: Unhandled class: 0x45 (THERMOSTAT FAN STATE), NodeID: 9 (0x09), Index: 0, Instance: 1

Thanks.

**Comment by gwmullin** [comment]
Re: Modes - In my testing openzwave correctly retrieves the modes from the thermostat (and my thermostat reports a 'Resume' mode, which you are missing here)

Re: Product type and ID - I am only configuring the thermostat I was able to test, and the type and id fields were reported by my thermostat to the controller - It sounds like you may have a different thermostat (particularly if you do not have the 'Resume' mode).

Re: unhandled class - your application should handle these classes, the library is complaining that there is no handler for the classes mentioned.

**Comment by raym777** [comment]
Ok. It looks like the same product but slightly different (possibly region specific). Is it best I provide a separate config which i have successfully tested for my specific modell, rather than merging with yours?

**Comment by gwmullin** [comment]
Likely a good idea

**Comment by gwmullin** [comment]
@Fishwaldo Any chance for a quick peek at this to see if anything needs to be changed?

**Comment by Fishwaldo** [comment]
@gwmullin I'll merge soon. What about @raym777 comments? A separate config file for that device coming?

**Comment by raym777** [comment]
@Fishwaldo The config I've tested and working for my device is below. Sorry, a bit new to all this so let me know if I need to raise a new request.

`<Product type="0202" id="8031" name="ZTS-110" config="remotec/zts-110.xml"/>`

`<?xml version="1.0" encoding="utf-8"?>
<Product xmlns='http://code.google.com/p/open-zwave/'>

	
	
	<CommandClass id="67" base="0" getsupported="false"/>

	<CommandClass id="64" name="COMMAND_CLASS_THERMOSTAT_MODE" version="1" request_flags="4" create_vars="true">
		<Value type="list" genre="user" instance="1" index="0" label="Mode" units="" read_only="false" write_only="false" min="0" max="0" value="0">
			<Item label="Off" value="0" />
			<Item label="Heat" value="1" />
			<Item label="Cool" value="2" />
			<Item label="Auto" value="3" />
		</Value>
		<SupportedModes>
			<Mode index="0" label="Off" />
			<Mode index="1" label="Heat" />
			<Mode index="2" label="Cool" />
			<Mode index="3" label="Auto" />
		</SupportedModes>
	</CommandClass>
  
	<CommandClass id="112">
		<Value type="int" index="1" genre="config" label="Swing" min="1" max="4" value="2">
			<Help>1 =  1 F / 0.5 C; 2 =  2 F / 1.0 C (default); 3 =  3 F / 1.5 C; 4 =  4 F / 2.0 C</Help>
		</Value>
		<Value type="int" index="2" genre="config" label="Differential" value="2">
			<Help>1 =  1 F / 0.5 C; 2 =  2 F / 1.0 C (default); 3 =  3 F / 1.5 C; 4 =  4 F / 2.0 C</Help>
		</Value>
		<Value type="int" index="3" genre="config" label="Set filter counter" min="500" max="4000" value="500">
			<Help>500 to 4000 hours. Default = 500 hours. Resolution = 100 hours.</Help>
		</Value>
		<Value type="int" index="4" genre="config" label="Report filter counter" value="0">
			<Help>Read only. 0-9999 hours.</Help>
		</Value>
		<Value type="int" index="5" genre="config" label="Temp scale" value="0">
			<Help>0=Celcius, 1=Farenheit</Help>
		</Value>
		<Value type="int" index="6" genre="config" label="Upper limit of heat set point" value="240">
			<Help>Example 24; input = 240</Help>
		</Value>
		<Value type="int" index="7" genre="config" label="Lower limit of cool set point" value="180">
			<Help>Example 18; input = 180</Help>
		</Value>
		<Value type="int" index="11" genre="config" label="Trigger auto report (room temp)" min="1" max="8" value="0">
			<Help>Trigger AUTO report if room temperature is different from last report. (It will report room temperature only). 0 = disable AUTO report if room temperature is different from last report; 1 = 1 F (0.5 C); 2 = 2 F (1.0 C); 3 = 3 F (1.5 C); 4 = 4 F (2.0 C), (default); 5 = 5 F (2.5 C); 6 = 6 F (3.0 C); 7 = 7 F (3.5 C); 8 = 8 F (4.0 C)</Help>
		</Value>
		<Value type="int" index="12" genre="config" label="Trigger auto report (time)" min="1" max="16" value="0">
			<Help>AUTO report by time interval. (It will report room temperature only). 0 = disable AUTO report function (by time interval); 1 = 0.5 hr; 2 = 1.0 hr; 3 = 1.5 hrs; 4 = 2.0 hrs; 5 = 2.5 hrs; 6 = 3.0 hrs; 7 = 3.5 hrs; 8 = 4.0 hrs; 9 = 4.5 hrs; 10 = 5.0 hrs; 11 = 5.5 hrs; 12 = 6.0 hrs; 13 = 6.5 hrs; 14 = 7.0 hrs; 15 = 7.5 hrs; 16 = 8.0 hrs</Help>
		</Value>
		<Value type="int" index="14" genre="config" label="Dead band" value="4">
			<Help> </Help>
		</Value>
	</CommandClass>

  	
  	<CommandClass id="133">
   		 <Associations num_groups="3">
      			<Group index="1" max_associations="5" label="Heat pump" />
      			<Group index="2" max_associations="5" label="Compressor" />
      			<Group index="3" max_associations="5" label="Auto report" auto="true" />
   		 </Associations>
  	</CommandClass>

</Product>
`

**Comment by Fishwaldo** [comment]
@raym777 Could you open a new PR with the changes for your device?

**Comment by Fishwaldo** [comment]
@gwmullin Thanks!

**Pull request merged**
