### PR TITLE
Fibaro FGBS-222 Smart Implant

### PR DESCRIPTION
**Pull request by f-bor**
Changes for Fibaro FGBS-222 Smart Implant

Module: https://www.fibaro.com/us/products/smart-implant/
Documentation: https://manuals.fibaro.com/content/manuals/en/FGBS-222/FGBS-222-EN-T-v1.0.pdf

Everything seems working fine to me, except lifeline association. I have to enable the polling to get updated values. I don't have enough zwave knowledge to find what is wrong.

### CODE REVIEW

**Comment by f-bor** [comment]
After more tests, if I include the module using secure mode, there seems to be a problem during the zwave capabilities or variables enumeration. I mean that I end up with only one input, one output, and the internal temperature. If I include the module without secure mode, the association with the controller takes a lot more time and I end up with everything detected properly (but without automatic status updates).

**Comment by Fishwaldo** [comment]
Probably related to #1639 based on your comments.

**Comment by f-bor** [comment]
ah it's funny : I have a ZMNHXD1 on my desk just waiting to be wired and put into service :)

Should I open an issue and provide the same logs you asked for #1639 ?

**Comment by eltoro81** [comment]
Looking forward to get this device added. Thanks for your help @f-bor. I´m getting my device in a week or two and will also test. Although my Z-Wave skills are very limited...

**Comment by f-bor** [comment]
hi @eltoro81,

I'm in the EU too. I won't have time to really work on this until next month.

The id 32 is for zwave COMMAND_CLASS_BASIC. You can easily find information on its purpose on internet (for example: https://www.vesternet.com/resources/technology-indepth/how-z-wave-controllers-work/).
Endpoints (id 96) are for getting information on sensors and switches (see COMMAND_CLASS_MULTI_CHANNEL).

**Pull request merged**
