### PR TITLE
Several Config Parameter Fixes for LZW30, LZW30-SN, LZW31, LZW31-SN, LZW36

### PR DESCRIPTION
**Pull request by InovelliUSA**

### CODE REVIEW

**Comment by stshontikidis** [comment]
Any status on this?

**Comment by InovelliUSA** [comment]
The request seems to still be in queue to be looked at. I don't think there is anything else Inovelli needs to do, but let me know if this is not the case.

**Comment by InovelliUSA** [comment]
I've added an update to the lzw36 config file to add config options for parameter 51 that is in firmware 1.36+

**Comment by Myztillx** [comment]
Is there something else that needs to happen to get this merged? Would really like this update 😁

**Comment by judeibe** [comment]
Looking forward to seeing the pull request merged in.

**Comment by Fishwaldo** [comment]
Thanks!

**Pull request merged**
