### PR TITLE
Neo Coolcam Power Plug

### PR DESCRIPTION
**Pull request by LouiS22**
Initial xmls for Neo Coolcam Power Plug

### CODE REVIEW

**Comment by nechry** [comment]
please check my updated files

**Comment by LouiS22** [comment]
Copy that!

Sorry for the mistaktes, this was my first ever github commit...

2016-08-18 14:02 GMT+02:00 Jean-François Auger <notifications@github.com>:

**Comment by nechry** [comment]
No problems, accept my changes and I will perform the PR

**Comment by nechry** [comment]
You don't have to open a new PR

**Comment by LouiS22** [comment]
Oh sorry, I don't know how can I accept your changes :D

2016-08-18 14:15 GMT+02:00 Jean-François Auger <notifications@github.com>:

**Comment by nechry** [comment]
http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request

**Comment by nechry** [comment]
in your fork you have 2 PR accept them

**Comment by LouiS22** [comment]
Done, sorry for being lame :)

2016-08-18 14:19 GMT+02:00 Jean-François Auger <notifications@github.com>:

**Pull request merged**
