### PR TITLE
update Smart Energy Switch G5

### PR DESCRIPTION
**Pull request by nechry**
thank to Gert Boer for the fix

### CODE REVIEW

**Comment by ualex73** [comment]
Any reason why the "<Protocol refreshonnodeinfoframe="false"/>" is removed?

**Comment by nechry** [comment]
Ho... No reason, I will fix it.

**Comment by nechry** [comment]
I will close the PR and sumit a good one.

**Comment by Fishwaldo** [comment]
Please don't remove the basic CC. It works fine with it included. 

On 7 Jun, 2015, at 7:03 pm, "Jean-François Auger" <notifications@github.com <mailto:notifications@github.com> > wrote:

I will close the PR and sumit a good one.

**Comment by nechry** [comment]
Yes, next time I check tree time config from some one else.

**Comment by nechry** [comment]
oki done with https://github.com/OpenZWave/open-zwave/pull/595
start over from original to much mistake in new version

**Pull request closed without merging**
