### PR TITLE
Added brand Sunricher and moved miscategorized devices

### PR DESCRIPTION
**Pull request by TheRealLouCipher**
The devices where miscategorized as Tronika which is not a manufacturer. These devices are Sunricher. Created new folder sunricher and moved files from tronika folder to there.

### CODE REVIEW

**Comment by nechry** [comment]
You remove 2 devices entries in Manufacturer file

**Comment by TheRealLouCipher** [comment]
Sorry, my mistake. Not sure of the id's of those two devices but I think it's better to keep them in the file but under the brand Sunricher. I added them again to the manufacturer file.

**Comment by nechry** [comment]
thank, 
one last thing, can you also update the distfiles.mk file, remove old entries and add the news one, this will avoid a test job failure.

https://github.com/OpenZWave/open-zwave/blob/master/distfiles.mk#L494

**Comment by TheRealLouCipher** [comment]
Sure, i'll do that. I need to close this PR and do a new one right, after the changes?

**Comment by nechry** [comment]
thank @TheRealLouCipher

**Pull request merged**
