### PR TITLE
Add ZWP PA-100 support

### PR DESCRIPTION
**Pull request by emc2cube**
Add support for zwaveproducts.com Plug-In Appliance Module, ZL-PA-100 https://www.zwaveproducts.com/shop/z-wave-lighting/z-wave-plugin-modules/zlink-products-plug-in-appliance-module-zl-pa-100

### CODE REVIEW

**Comment by emc2cube** [comment]
One line of this commit, on manufacturer_specific.xml, ended up being deleted somewhere in a later merge. Can you add it back?
I can open a new pull request if needed.

https://github.com/OpenZWave/open-zwave/pull/1763/commits/ed26aee60938463ca45439c28ab67b2298e5e1f2#diff-4f9a7693a2910f1be50ca19ab57e3f92

**Comment by petergebruers** [comment]
Hi! You are probably referring to the "master" branch of OZW, which is now "Version 1.6". This branch uses a new config format. If you are still on "Version 1.4" then the file is still there, but you have to check out the "1.4" branch.

**Comment by emc2cube** [comment]
I see. As the file "config/zwp/PA-100.xml" was present in both 1.4 and 1.6, while the "manufacturer_specific.xml" lost the reference to PA-100 in 1.6 I guessed it was lost somewhere in between merges.
Seems domoticz now use 1.6 and by manually adding the reference of PA-100 back to manufacturer_specific.xml it does the trick, for now.

**Comment by petergebruers** [comment]
Ah, you're running the Domoticz beta, that is OZW 1.6 indeed. Make sure you check activity on their forum + github issue tracker, both OZW and Domoticz still get updates. The config file is there, but has not been fully updated (you can compare it with WD-100 and notice it does not have "metadata"). I am very new to this myself but I'll get it sorted.

**Comment by emc2cube** [comment]
Got it. Well this may help then.
Seems to work on my domoticz install  ;)

[PA-100.xml.txt](https://github.com/OpenZWave/open-zwave/files/3271625/PA-100.xml.txt)

**Comment by petergebruers** [comment]
Thanks!

**Pull request merged**
