### PR TITLE
Added parameter 6, removed parameter 5

### PR DESCRIPTION
**Pull request by petrovcicklemen**
The MiniDimmer device will be recertified. This new revision removes parameter 5, which is replaced by parameter 6.

### CODE REVIEW

**Comment by nechry** [comment]
@petrovcicklemen can you add the revision log entry for your updated version

**Comment by petrovcicklemen** [comment]
> @petrovcicklemen can you add the revision log entry for your updated version

@nechry Do you mean the <MetaData><ChangeLog><Entry> element or someting else?

**Comment by nechry** [comment]
> > @petrovcicklemen can you add the revision log entry for your updated version
> 
> 
> 
> @nechry Do you mean the `<MetaData><ChangeLog><Entry>` element or someting else?

yes exactly

**Comment by petrovcicklemen** [comment]
> > > @petrovcicklemen can you add the revision log entry for your updated version
> > 
> > 
> > @nechry Do you mean the `<MetaData><ChangeLog><Entry>` element or someting else?
> 
> yes exactly

@nechry  Done.

**Comment by nechry** [comment]
thank @petrovcicklemen

**Comment by rezzalex** [comment]
> The MiniDimmer device will be recertified. This new revision removes parameter 5, which is replaced by parameter 6.

Hello.
What is this recertification ?
I have a mini dimmer (software version 2), and experience issues when using 2 physical  switches (no pb with only one).

Am I concerned ?

**Comment by petrovcicklemen** [comment]
>What is this recertification ?
The product will be recertified to support also the SmartStart inclusion feature, that was requested by one of our major customers. Apart from that, the change this PR describes was also done, so that the user doesn't have to reinclude the device.

>I have a mini dimmer (software version 2), and experience issues when using 2 physical switches (no pb with only one). Am I concerned ?
Apologies for not replying to you. My colleague, who handles support, was OoO last couple of days, but will be back tomorrow, so he'll probably answer to your ticket tomorrow on the official support portal.

**Pull request merged**
