### PR TITLE
Heatit zdim

### PR DESCRIPTION
**Pull request by paalkr**
Adding configuration for the Heatit Z-Dim device
https://www.heatit.com/z-wave/heatit-z-dim/

The config is tested and is working with the latest beta build of Domoticz. Also working using the Open Zwave GUI app.

### CODE REVIEW

**Comment by paalkr** [comment]
I would very much like to get this PR merged. Can anybody explain why the png did fail the integration test?

**Comment by gertvdijk** [comment]
(Same boat here.)

All PRs are failing at the moment (all of my three are) with the unrelated `Password is not specified` error.

Despite build errors, PRs were merged in the past anyway. :man_shrugging: 

<sub>Also: interesting product.</sub>

**Comment by petergebruers** [comment]
I'll have a look at it, probably today.

**Comment by petergebruers** [comment]
The builds fail because of a build server, don't worry about that...

The xml has issues with non-utf8 encoded characters

heatit-zdim.xml:14: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0x95 0x20 0x5A 0x2D
� Z-wave rotary dimmer

I'll see if I can fix it.

**Comment by petergebruers** [comment]
Thanks! Squash-merged...

**Comment by paalkr** [comment]
Thanks for fixing the non utf-8 characters.

BTW, the HeatIt Z-Dim device is just the best z-wave light dimmer switch available. The WAF factor increases dramatically.

**Pull request merged**
