### PR TITLE
Add Shenzhen Neo PD03Z device, replaces the PD02Z which is wrong

### PR DESCRIPTION
**Pull request by aretakisv**
PD03Z device is covering the IDs 0003:108d and 0003:208d for manufacturer 0258

Based on manual:
Moved Parameter 10 to 11 ( enable disable Led )
Added Parameter 10 which adjusts the temperature report threshold
Added 99 which is the sensor calibration for Luminance

### CODE REVIEW

**Comment by petergebruers** [comment]
Thank you for contributing. 

Please read my comments and discuss further the issue here, solving the problem probably isn't as easy as you think:

https://github.com/OpenZWave/open-zwave/issues/2083

You'll understand I cannot merge this without proper investigation and conclusion...

**Comment by aretakisv** [comment]
What I am saying is.
I am trying to add the new device on 1.4 version of openzwave and your changes. which do not exist.
This impacts HASS.

the new device list is not picked by the python_openzwave. and on my HASS i still see only 10 params even with PD02Z

**Comment by petergebruers** [comment]
A few things...

It does not look like my patch, that is not how I remember it, but I must admit I have not run a" diff", please make sure you do not break existing config of NAS PD02 owners!

OpenZWave 1.4 is no longer supported, @Fishwaldo will agree the way forward is OpenZWave 1.6, so we tend to spend not much energy on 1.4

And lastly, HASS does not use this repository, they have forked OpenZWave 1.4, so if you want it on HASS then you'll have to open a PR here:

https://github.com/home-assistant/open-zwave

If you can guarantee that this PR is sane and won't break stuff than I'll accept it though.

**Comment by aretakisv** [comment]
Tganks for the update, I think I will close this one as makes no sense to do so.
I will take your changes and Device PD03Z in order to apply them to Home assistant. I will also submit an addition for PD03Z, for 1.6

**Comment by petergebruers** [comment]
Thanks!

**Pull request closed without merging**
