### PR TITLE
Add Mcohome MH-S411 & MH-S412

### PR DESCRIPTION
**Pull request by Warp95**

### CODE REVIEW

**Comment by nechry** [comment]
@Warp95 we will merge all jeedom configuration file so you don't need to do each PR

**Comment by Warp95** [comment]
@nechry when will you do it ? because I have an urgent need for these two devices.

**Comment by sarakha63** [comment]
warp95 : the need is for Jeedom or another solution ?

**Comment by nechry** [comment]
Normally tonight, we have lot of configuration to merger, some news devices and many fix on existing device. The PR will be send by @sarakha63

**Comment by Warp95** [comment]
sarakha63@ the need is for Domoticz.

**Comment by Warp95** [comment]
@sarakha63 could you add Mcohome MH-S411 & MH-S412, please !

**Comment by nechry** [comment]
I did not fully completed the configuration validation for mcohome family. I prefer not yet released a bad or not completed configuration files.

**Comment by openzwave-dev-watcher** [comment]
when you think you have done? You want help ?

**Comment by Warp95** [comment]
when you think you have done? You want help ?

**Comment by Warp95** [comment]
when you think you have done? You want help ?

**Comment by nechry** [comment]
I tested the mh-s412 and he work well with the provided configuration in jeedom PR.
Do you also work with mh-s314? I fight a lot with multiInstance, no way to got a right return on each instances.

**Comment by Warp95** [comment]
Not sorry, I only work with the MH-S411 & MH-S412, the others are not distributed in France.
You can validate the two only ? Firstly ?

**Comment by nechry** [comment]
You ask from my side? Or ozw ?

**Comment by Warp95** [comment]
I request OZW kindly add my two devices ! please !!!!

**Comment by Warp95** [comment]
Can you add Mcohome MH-S411 & MH-S412, please ?

**Comment by sarakha63** [comment]
We already told you, the pull request is submitted. You just have to wait Justin to review it and accept it. THe pull request is quite big so it  takes some time for justin to review it

**Pull request closed without merging**
