### PR TITLE
Make libudev dependency optional

### PR DESCRIPTION
**Pull request by gkroone**
I understood from @Fishwaldo that there's no major functionality loss without libudev.

As libudev is not available on all linux platforms, I would like to propose making this optional. 

I am not very experienced in programming, so probably there's prettier ways to get this done, but could you considder making libudev an optional dependency, e.g by passing an environment variable NOLIBUDEV  with make like done in this PR?

Regards,

Geert

### CODE REVIEW

**Comment by Fishwaldo** [comment]
Thanks. I'll look at incorporating this soon.

**Comment by Diaoul** [comment]
Hi, any updates on this? Can I do anything to help?

**Comment by Fishwaldo** [comment]
I'll get to it eventually. Hang tight.

**Comment by Fishwaldo** [comment]
Hi,
Apologies, I just cleaned up the repo, removing old object files from way back when. This has resulted in PR's being messed up. Could you please redo the PR after pulling a new fork (the repo should be much smaller now though)

Thanks

**Pull request closed without merging**
