### PR TITLE
Add Ecolink WaterFreeze Sensor information

### PR DESCRIPTION
**Pull request by fborotknetik**

### CODE REVIEW

**Comment by Fishwaldo** [comment]
You have just copied zwcfg entries which is not correct. Please read https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by fborotknetik** [comment]
actually this setup works fine for us:
1- manufacturer_specific.xml file, I added a new entry under ecolink for the water freeze sensor

2- I modified the "ecolink/firefighter.xml" with the entries present in the "zwcfg_<zone_id>.xml" based on the autodiscovery for that device, but I also had to add two lines inside the "COMMAND_CLASS_SENSOR_BINARY" section:
this one 
		<Value type="bool" genre="user" instance="1" index="1" label="SensorFreeze" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />

and 
		<SensorMap index="1" type="7" />

[ecolink-water-sensor.pdf](https://github.com/OpenZWave/open-zwave/files/2519289/ecolink-water-sensor.pdf)
based on this doc from the manufacturer

**Comment by Fishwaldo** [comment]
Almost everything in the Config filr you provided us ignored as it’s auto discovered. That’s why it works “fine”. 

What the config file is for us configuration values and association details which your PR does not include. 

So it’s not correct. Please read the link I provided and resubmit

**Comment by fborotknetik** [comment]
It is ok, for some reason when copying the 2 new lines github does not show them, anyways these are the new lines I talked about

In themanufacurer_specific.xml file to add the new device not present in the database:

                <Manufacturer id="014a" name="Ecolink">
                                <Product type="0001" id="0001" name="Motion Sensor" config="ecolink/sensor.xml"/>
                                <Product type="0001" id="0002" name="Door/Window Sensor" config="ecolink/doorwindow.xml"/>
                                <Product type="0001" id="0003" name="Tilt Sensor" config="ecolink/sensor.xml"/>
                                <Product type="0004" id="0001" name="Motion Detector" config="ecolink/motion.xml"/>
                                <Product type="0004" id="0002" name="Door/Window Sensor" config="ecolink/doorwindow.xml"/>
                                <Product type="0004" id="0003" name="Garage Door Tilt Sensor" config="ecolink/sensor.xml"/>
                                <Product type="0005" id="000f" name="FireFighter" config="ecolink/firefighter.xml"/>
                                <Product type="0005" id="0010" name="Flood/Freeze Sensor" config="ecolink/waterfreezesensor.xml"/>
                </Manufacturer>


And in the waterfreezesensor.xml file, I added the red lines inside the COMMAND_CLASS_SENSOR_BINARY section, everything else in the file is auto discovered but for the freeze event to work you have to add those lines if you don’t you wont receive them


                <CommandClass id="48" name="COMMAND_CLASS_SENSOR_BINARY" version="1" request_flags="4" innif="true">
                                <Instance index="1" />
                                <Value type="bool" genre="user" instance="1" index="0" label="SensorFlood" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
                                <Value type="bool" genre="user" instance="1" index="1" label="SensorFreeze" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False" />
                                <SensorMap index="0" type="6" />
                                <SensorMap index="1" type="7" />
                </CommandClass>




Fabian Borot
Sr. Software Engineer

Office:  +1-305-938-5400 x 153
Mobile: +1-305-588-6662
Skype/IM:
CIMA Group Building
1728 SW 22nd Street 6th Floor
Miami, Florida 33145
fborot@auris.com<mailto:fborot@auris.com>  www.auris.com<http://www.auris.com/>

A CIMA Group company www.cimagroup.com<http://www.cimagroup.com/>

[http://www.auris.com/signature/auris_logo.jpg]

CONFIDENTIALITY NOTICE: All information transmitted hereby is intended only for the use of the addressee(s) named above and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution of confidential and/or privileged information is prohibited. If the reader of this message is not the intended recipient(s) you are hereby notified that you must not read this transmission and that disclosure, copying, printing, distribution or use of any of the information contained in or attached to this transmission is prohibited. Anyone who receives confidential and/or privileged information in error should notify us immediately by replying to the sender of the message, mail the original message to us at the above address and destroy all copies.

[http://www.auris.com/signature/banner.jpg]

**Comment by Fishwaldo** [comment]
> it’s not correct. Please read the link I provided and resubmit

**Comment by johntdyer** [comment]
@gaganinvic / @fborotknetik - Any chance you guys plan to resubmit this ?

**Pull request closed without merging**
