### PR TITLE
Marko marjamaa fortrezz wwa02

### PR DESCRIPTION
**Pull request by MarkoMarjamaa**
Added Fortrezz WWA-02 Water and Temperature Alarm

### CODE REVIEW

**Comment by nechry** [comment]
Your wwa02.xml file is invalide, please check the Wiki
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by MarkoMarjamaa** [comment]
Can you be more specific? I just copied the file from zwcfg_XXXX.xml. 

This device has been around for more than 5 years and nobody's bothered to add it to database. I just needed my system to get the product name right.

**Comment by nechry** [comment]
the zwcfg cache file is not a configuration file. 
in a device specific configuration file we wan all parameters and association groups.
also in some case we must add special rules with command classes.

if is just for the product name only the manufacturer_specific.xml is require without the wwa02.xml

**Comment by MarkoMarjamaa** [comment]
Can you be more specific? I just copied the file from zwcfg_XXXX.xml. 

This device has been around for more than 5 years and nobody's bothered to add it to database. I just needed my system to get the product name right.

**Comment by nechry** [comment]
@MarkoMarjamaa  You will open a new PR with the right files?
If not I will create the config file

**Comment by MarkoMarjamaa** [comment]
I closed this pull request to make those changes to make new pull request and at the same time, you made those changes to master? 
Wow.

**Comment by nechry** [comment]
sorry I'm to speed, but with this file you see more what we expect in a config file.

**Comment by MarkoMarjamaa** [comment]
Didn't know this was a competition. 
So, I just spent a hour figuring this out for nothing.

**Comment by nechry** [comment]
I did just for helping you, is I kwon you will take on this. I just wish now you know the file content we expect. If you lear something you didn't loose your time.

**Pull request closed without merging**
