### PR TITLE
Added in the DotNet ZWManager the GetVersionLongAsString method

### PR DESCRIPTION
**Pull request by PascalPiche**

### CODE REVIEW

**Comment by nechry** [comment]
@PascalPiche try to don't mix code and config file in same PR, if you wan't a quick merge for the device config file.

**Comment by Fishwaldo** [comment]
@PascalPiche This PR has a lot of extra commits in it from the master branch. Could you please rebase on the Dev branch instead.

**Comment by PascalPiche** [comment]
Will fix this pr after the merge of Sync dot net zw manager bundle for avoiding conflicts,

**Comment by Fishwaldo** [comment]
The Sync one has merged. Can you fix this one up?

**Comment by Fishwaldo** [comment]
Hi,
Apologies, I just cleaned up the repo, removing old object files from way back when. This has resulted in PR's being messed up. Could you please redo the PR after pulling a new fork (the repo should be much smaller now though)

Thanks

**Pull request closed without merging**
