### PR TITLE
Small update and verify with version 2.5

### PR DESCRIPTION
**Pull request by pepeEL**

### CODE REVIEW

**Comment by nechry** [comment]
@pepeEL he try to simplify configuration label. I think is better to use the help element to explain the the meaning of a parameter.

**Comment by pepeEL** [comment]
What do you mean ?

**Comment by Fishwaldo** [comment]
The label is too long. Try to use a short description, and put more information into the help text.

**Comment by piokuc01** [comment]
I use it the same from manual fibaro.

**Comment by pepeEL** [comment]
I use it as the same in manual fibaro

**Comment by nechry** [comment]
yes but sometime the "official" label are too long and can be more precise with few words.

**Comment by Fishwaldo** [comment]
Think about it from a GUI perspective. A long label can make GUI's look really bad. :)

**Comment by Fishwaldo** [comment]
Hi,
Apologies, I just cleaned up the repo, removing old object files from way back when. This has resulted in PR's being messed up. Could you please redo the PR after pulling a new fork (the repo should be much smaller now though)

Thanks

**Pull request closed without merging**
