### PR TITLE
added new command class ManufacturerProprietary for Fibaro FGRM-222 (part 2)

### PR DESCRIPTION
**Pull request by ChristianKuehnel**
As discussed some time ago in the forum: The Fibaro FGRM-222 Roller Shutter 2 is using the COMMAND_CLASS_MANUFACTURER_PROPRIETARY to indicate the tilt angle of the slats. This is only transmitted when activating the venetian blind mode and setting the report type to "Fibaro Command class".

@Fishwaldo 
As I messed up my branch completely, it was easier to create a new, clean one. So this is the continuation of pull request https://github.com/OpenZWave/open-zwave/pull/1203

### CODE REVIEW

**Comment by ChristianKuehnel** [comment]
As I did not get any feedback on the design/architecture, I implemented the remaining features in the same way.

I tested these successfully with my devices:
* handling of received messages is working
* requesting the values is working
* setting the position and tile of the venetian blinds is also working

**Comment by Fishwaldo** [comment]
Thanks

**Comment by ChristianKuehnel** [comment]
Hi @Fishwaldo,

what do I have to do to get this merged to master? I would like to use it in Home Assistant and they are using the python-openzwave library which seems to be using some snapshots from master.
 https://github.com/OpenZWave/python-openzwave/tree/master/archives

**Comment by andre-richter** [comment]
Hi @nechry,

I tried to follow all kinds of resources to understand why this change is not being merged into master. From what I understand, it is sitting in the DEV branch that is supposed to be merged into master. Unfortunately, this seems to be dormant since over a year now.

Same as @ChristianKuehnel, I would be super happy to see this in main, because like him, I am using Home Assistant with lots of Fibaro Roller shutters and would really like to get control over the slat angle. I'm sure there's lots of other users that would profit from this as well.

Kindly let us know if there is anything that we can help you with to accelerate getting this merged.

Thanks a lot,
Andre

**Comment by tameike000** [comment]
@ChristianKuehnel Do I read it correctly your fix is still stitting in the dev branch and is a target for 1.6 (currently we are still on 1.4?)

How did you integrate it into HA? Don't mind to install the dev branch. I really want that fix.

Thanks.
M

**Comment by petergebruers** [comment]
The FGRM-222 Venetian Blind mode is supported in OpenZWave 1.6 and is working, you can test with "ozwcp". I know this because I own one. But HASS is still using a fork of 1.4.

I opened a PR to add Venetian blind support to Domoticz beta, but it was not accepted yet because it requires changes to Domoticz device handling.

So I am not sure which software actually supports Venetian blind mode right now...

**Comment by tameike000** [comment]
@petergebruers Thanks for the heads up. I will raise it in HA!

**Pull request merged**
