### PR TITLE
Sync dot net zw manager bundle

### PR DESCRIPTION
**Pull request by PascalPiche**
Added new methods in the dotnet adapter : IsNodeZWavePlus, GetNodeDeviceType, GetNodeDeviceTypeString, GetNodeRole, GetNodeRoleString, GetNodePlusType, GetNodePlusTypeString, GetValueMin, GetValueMax, IsValueWriteOnly, GetChangeVerified, GetGroupLabel. Some comments fix also and const params added.

Fixed also some comments and unifiying some space between ) and {

### CODE REVIEW

**Comment by Fishwaldo** [comment]
@PascalPiche This PR has a lot of extra commits in it from the master branch. Could you please rebase on the Dev branch instead.

**Comment by PascalPiche** [comment]
Fixed PR with only the commit in concern

**Comment by Fishwaldo** [comment]
Looks good. I'll merge soon.

**Comment by Fishwaldo** [comment]
Thanks!

**Comment by toby11** [comment]
Hi, have these new ZWavePlus methods been moved in to the dotnet wrapper? I have just got the latest master and they do not seem to be there?

thanks

**Pull request merged**
