### PR TITLE
Fix config values for Aeotec Nano Shutter

### PR DESCRIPTION
**Pull request by matejdro**
* Trip times were decimal while they should be short
* Added actual list items to the repositioning and confirmation triggers

### CODE REVIEW

**Comment by matejdro** [comment]
Question: Is there a better way to define those one-shot triggers like repositioning and calibration configs here? Currently it is represented by two list items and to trigger reposition, you have to switch between those items and then switch again.

**Comment by kpine** [comment]
> Question: Is there a better way to define those one-shot triggers like repositioning and calibration configs here? Currently it is represented by two list items and to trigger reposition, you have to switch between those items and then switch again.

I think that is usually done with the button type (which doesn't seem to be documented in the wiki). For example:
https://github.com/OpenZWave/open-zwave/blob/189b9050ee857bc177a26973cd99b81ebc9fcd92/config/aeotec/zw096.xml#L135

If you're using ozwdaemon, button values are not currently functioning properly.

**Comment by matejdro** [comment]
Should I change it up to the button to be the most correct or leave it as list to keep compatibility with ozwdaemon?

**Comment by nechry** [comment]
> Should I change it up to the button to be the most correct or leave it as list to keep compatibility with ozwdaemon?

Keep it as list even is not user-friendly, but rename default item to "Default".
Please also add a Change Log Entry for your revision

**Comment by matejdro** [comment]
Made both updates.

**Comment by Fishwaldo** [comment]
Thanks!

**Pull request merged**
