### PR TITLE
Update fgd212.xml

### PR DESCRIPTION
**Pull request by nouknouk**
- Fibaro FGD 212, config value index=31 (Load control mode recognized during auto-calibration): changed label, was a duplicate with index=30

- Fibaro FGD 212, config value index=32 (On/Off mode): fixed incorrect help string

cf. issue #1854

### CODE REVIEW

**Comment by nouknouk** [comment]
also bumped revision number

**Comment by petergebruers** [comment]
Thank you for contributing. Almost ready to merge...
Can you add a revision entry to the end of the section ```<ChangeLog>```

Then I would change:
```
<Help>Enable for non-dimmable light sources. Forced auto-calibration will set this parame-ter’s value to 2.</Help>
```

To match the Fibaro manual:

```
<Help>This mode is necessary while connecting non-dimmable light sources. Setting this parameter to 1 automatically ignores brightening/dimming time settings. Forced auto-calibration will set this parameter’s value to 2</Help>
```

Then run "make xmltest" - it will tell you if the edits are OK.

Then push the xml file and also testconfigversions.cfg file.

An explanation of the process in more detail is on the wiki:

https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by petergebruers** [comment]
@nouknouk don't worry about it, I'll make the changes for you.

**Comment by nouknouk** [comment]
> Thank you for contributing. Almost ready to merge...
> Can you add a revision entry to the end of the section `<ChangeLog>`
> 
> Then I would change:
> 
> ```
> <Help>Enable for non-dimmable light sources. Forced auto-calibration will set this parame-ter’s value to 2.</Help>
> ```
> 
> To match the Fibaro manual:
> 
> ```
> <Help>This mode is necessary while connecting non-dimmable light sources. Setting this parameter to 1 automatically ignores brightening/dimming time settings. Forced auto-calibration will set this parameter’s value to 2</Help>
> ```
> 
> Then run "make xmltest" - it will tell you if the edits are OK.
> 
> Then push the xml file and also testconfigversions.cfg file.
> 
> An explanation of the process in more detail is on the wiki:
> 
> https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

Thanks Peter for your corrections ; I should have done them myself, but I was unavailable last days.

For the `<help>` tag, I cut some parts because I didn't know if there was any implicit limit in string's length for this field ; if there isn't any limit, for sure the original Fibaro description is better.

Also thanks for your explanations & link about the process ; I'll take care of them for any future change.

Regards.

**Pull request merged**
