### PR TITLE
BeNext TagReader500 config files

### PR DESCRIPTION
**Pull request by hvbommel**
BeNext TagReader500 config files for Dev branch

### CODE REVIEW

**Comment by nechry** [comment]
Please run make xmltest before submit your PR, the xml file contains non ASCII characters

**Comment by hvbommel** [comment]
I ran xmltest. I get “OK” on both files (manufacturer_specific.xml and TagReader500.xml). “make xmltest” on the toplevel directory is failing however. See trace below.

 

xmltest manufacturer_specific.xml

Running test manufacturer_specific.xml ... OK

Saving response as manufacturer_specific.OK

 

xmltest TagReader500.xml

Running test TagReader500.xml ... OK

Saving response as TagReader500.OK

 

make xmltest

Makefile:40: *** xmllint command not found..  Stop.

 

Van: Jean-François Auger [mailto:notifications@github.com] 
Verzonden: zaterdag 4 maart 2017 22:03
Aan: OpenZWave/open-zwave <open-zwave@noreply.github.com>
CC: hvbommel <henri@vanbml.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [OpenZWave/open-zwave] BeNext TagReader500 config files (#1164)

 

Please run make xmltest before submit your PR, the xml file contains non ASCII characters

**Comment by nechry** [comment]
you must install requirement to do the test. I fixed your xml file

is my setup :
sudo apt-get install libxml2-utils
sudo apt-get install libxml-simple-perl
sudo apt-get install libxml-libxml-perl

**Comment by hvbommel** [comment]
Will do, thanks

 

Van: Jean-François Auger [mailto:notifications@github.com] 
Verzonden: zaterdag 4 maart 2017 23:09
Aan: OpenZWave/open-zwave <open-zwave@noreply.github.com>
CC: hvbommel <henri@vanbml.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [OpenZWave/open-zwave] BeNext TagReader500 config files (#1164)

 

you must install requirement to do the test. I fixed your xml file

is my setup :
sudo apt-get install libxml2-utils
sudo apt-get install libxml-simple-perl
sudo apt-get install libxml-libxml-perl

**Pull request merged**
