### PR TITLE
Update manufacturer_specific.xml

### PR DESCRIPTION
**Pull request by saintman23**
Corrected XML config filename for ' type="0400" id="0109" '

### CODE REVIEW

**Comment by nechry** [comment]
I'm not sur about this change, why you change de target definition but not the device name. they are 2 revisions of this device the new one 221 contains extra parameters.

**Comment by saintman23** [comment]
The file I changed was fgs221.xml, which is defenitely for Double Swich FGS221 (2x1,5kW). Not for Single Switch FGS211 (1x3kW)

**Comment by nechry** [comment]
we need also to rename the device name for a FGS-212

**Comment by saintman23** [comment]
Renamed to FGS211

**Comment by nechry** [comment]
is a old version?

**Comment by saintman23** [comment]
type="0400" is an old one.

**Pull request merged**
