### PR TITLE
Support for the BeNext TagReader500

### PR DESCRIPTION
**Pull request by hvbommel**
The new BeNext TagReader500 is using a variable Usercode length ranging form 4 up to 10 
digits and fails to work with the current OpenZWave implementation. The previous models where always using 10 digit, sometimes zero filled, usercodes. I have added the device to the xml files and updated UserCode.h & Usercode.cpp to support the new device.

### CODE REVIEW

**Comment by Fishwaldo** [comment]
what exactly is broken with the current UserCode CC? It works fine on other devices that are different lengths?

Anyway, the UserCode CC will be re-factored soon (see #1059), so could you split this PR into config changes and hang back on the UserCode changes till #1059 is done. I'll try to address anything thats broken into the #1059 changes.

**Comment by hvbommel** [comment]
In the previous code, when the user entered let say "1234" as the the code it was extended to 10 digits like "1234000000". So the reply to the device would be "1234000000" instead of "1234". The new BeNext TagReader500 does fail on this and therefore it does not set the code. The fix I made will do the following logical operations: 1. When 10 digits are received (key tags) all works as before. 2. When less then 10 digits are received, return the same less then 10 digits. 3. When less then 4 digits received zero fill to 4 digits and return value. Can you send me a note when I should do a new pull request ? The config changes only make sense after Usercode is updated.

**Comment by hvbommel** [comment]
Once 1059 is available I will retest & debug to see if my changes are still required. Looking at the code I think they still do as a Hardcoded user code length of 10 is used in Usercode.cpp

**Comment by hvbommel** [comment]
Hello Justin,

 

Do you have any idea if and when PR #1175 will be considered ? 

Or is there anything I can do to improve it so that it is easier to get it in ?

 

PS: I did the request on the master branch. Is it better when I resubmit the request on the Dev branch ?

 

Thanks

 

Henri

 

Van: Justin Hammond [mailto:notifications@github.com] 
Verzonden: woensdag 22 februari 2017 06:26
Aan: OpenZWave/open-zwave <open-zwave@noreply.github.com>
CC: hvbommel <henri@vanbml.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [OpenZWave/open-zwave] Support for the BeNext TagReader500 (#1151)

 

what exactly is broken with the current UserCode CC? It works fine on other devices that are different lengths?

Anyway, the UserCode CC will be re-factored soon (see #1059 <https://github.com/OpenZWave/open-zwave/pull/1059> ), so could you split this PR into config changes and hang back on the UserCode changes till #1059 <https://github.com/OpenZWave/open-zwave/pull/1059>  is done. I'll try to address anything thats broken into the #1059 <https://github.com/OpenZWave/open-zwave/pull/1059>  changes.

**Pull request closed without merging**
